In [2]:
import numpy as np
import pandas as pd
import warnings

warnings.filterwarnings('ignore')
pd.set_option('display.max_rows', None)    # Muestra todas las filas (para muchas columnas)
pd.set_option('display.max_columns', None) # Muestra todas las columnas
pd.set_option('display.width', None)       # Ajusta el ancho
pd.set_option('display.max_colwidth', None)# Muestra todo el contenido de cada celda

In [4]:
drivers_c = pd.read_csv('csv_limpios/drivers_c.csv')
drivers_updated_c = pd.read_csv('csv_limpios/drivers_updated_c.csv')

In [5]:
drivers_c

,driverRef,code,forename,surname,born,nationality,url
0,hamilton,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,heidfeld,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,rosberg,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,alonso,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,kovalainen,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
5,nakajima,NAK,Kazuki,Nakajima,1985-01-11,Japanese,http://en.wikipedia.org/wiki/Kazuki_Nakajima
6,bourdais,BOU,Sébastien,Bourdais,1979-02-28,French,http://en.wikipedia.org/wiki/S%C3%A9bastien_Bourdais
7,raikkonen,RAI,Kimi,Räikkönen,1979-10-17,Finnish,http://en.wikipedia.org/wiki/Kimi_R%C3%A4ikk%C3%B6nen
8,kubica,KUB,Robert,Kubica,1984-12-07,Polish,http://en.wikipedia.org/wiki/Robert_Kubica
9,glock,GLO,Timo,Glock,1982-03-18,German,http://en.wikipedia.org/wiki/Timo_Glock
10,sato,SAT,Takuma,Sato,1977-01-28,Japanese,http://en.wikipedia.org/wiki/Takuma_Sato
11,piquet_jr,PIQ,Nelson,Piquet Jr.,1985-07-25,Brazilian,"http://en.wikipedia.org/wiki/Nelson_Piquet,_Jr."
12,massa,MAS,Felipe,Massa,1981-04-25,Brazilian,http://en.wikipedia.org/wiki/Felipe_Massa
13,coulthard,COU,David,Coulthard,1971-03-27,British,http://en.wikipedia.org/wiki/David_Coulthard
14,trulli,TRU,Jarno,Trulli,1974-07-13,Italian,http://en.wikipedia.org/wiki/Jarno_Trulli
15,sutil,SUT,Adrian,Sutil,1983-01-11,German,http://en.wikipedia.org/wiki/Adrian_Sutil
16,webber,WEB,Mark,Webber,1976-08-27,Australian,http://en.wikipedia.org/wiki/Mark_Webber_(racing_driver)
17,button,BUT,Jenson,Button,1980-01-19,British,http://en.wikipedia.org/wiki/Jenson_Button
18,davidson,DAV,Anthony,Davidson,1979-04-18,British,http://en.wikipedia.org/wiki/Anthony_Davidson
19,vettel,VET,Sebastian,Vettel,1987-07-03,German,http://en.wikipedia.org/wiki/Sebastian_Vettel
20,fisichella,FIS,Giancarlo,Fisichella,1973-01-14,Italian,http://en.wikipedia.org/wiki/Giancarlo_Fisichella
21,barrichello,BAR,Rubens,Barrichello,1972-05-23,Brazilian,http://en.wikipedia.org/wiki/Rubens_Barrichello
22,ralf_schumacher,SCH,Ralf,Schumacher,1975-06-30,German,http://en.wikipedia.org/wiki/Ralf_Schumacher
23,liuzzi,LIU,Vitantonio,Liuzzi,1980-08-06,Italian,http://en.wikipedia.org/wiki/Vitantonio_Liuzzi
24,wurz,WUR,Alexander,Wurz,1974-02-15,Austrian,http://en.wikipedia.org/wiki/Alexander_Wurz
25,speed,SPE,Scott,Speed,1983-01-24,American,http://en.wikipedia.org/wiki/Scott_Speed
26,albers,ALB,Christijan,Albers,1979-04-16,Dutch,http://en.wikipedia.org/wiki/Christijan_Albers
27,markus_winkelhock,WIN,Markus,Winkelhock,1980-06-13,German,http://en.wikipedia.org/wiki/Markus_Winkelhock
28,yamamoto,YAM,Sakon,Yamamoto,1982-07-09,Japanese,http://en.wikipedia.org/wiki/Sakon_Yamamoto
29,michael_schumacher,MSC,Michael,Schumacher,1969-01-03,German,http://en.wikipedia.org/wiki/Michael_Schumacher
30,montoya,MON,Juan,Pablo Montoya,1975-09-20,Colombian,http://en.wikipedia.org/wiki/Juan_Pablo_Montoya
31,klien,KLI,Christian,Klien,1983-02-07,Austrian,http://en.wikipedia.org/wiki/Christian_Klien
32,monteiro,TMO,Tiago,Monteiro,1976-07-24,Portuguese,http://en.wikipedia.org/wiki/Tiago_Monteiro
33,ide,IDE,Yuji,Ide,1975-01-21,Japanese,http://en.wikipedia.org/wiki/Yuji_Ide
34,villeneuve,VIL,Jacques,Villeneuve,1971-04-09,Canadian,http://en.wikipedia.org/wiki/Jacques_Villeneuve
35,montagny,FMO,Franck,Montagny,1978-01-05,French,http://en.wikipedia.org/wiki/Franck_Montagny
36,rosa,DLR,Pedro,de la Rosa,1971-02-24,Spanish,http://en.wikipedia.org/wiki/Pedro_de_la_Rosa
37,doornbos,DOO,Robert,Doornbos,1981-09-23,Dutch,http://en.wikipedia.org/wiki/Robert_Doornbos
38,karthikeyan,KAR,Narain,Karthikeyan,1977-01-14,Indian,http://en.wikipedia.org/wiki/Narain_Karthikeyan
39,friesacher,FRI,Patrick,Friesacher,1980-09-26,Austrian,http://en.wikipedia.org/wiki/Patrick_Friesacher
40,zonta,ZON,Ricardo,Zonta,1976-03-23,Brazilian,http://en.wikipedia.org/wiki/Ricardo_Zonta
41,pizzonia,PIZ,Antônio,Pizzonia,1980-09-11,Brazilian,http://en.wikipedia.org/wiki/Ant%C3%B4nio_Pizzonia
42,matta,DAM,Cristiano,da Matta,1973-09-19,Brazilian,http://en.wikipedia.org/wiki/Cristiano_da_Matta
43,panis,PAN,Olivier,Panis,1966-09-02,French,http://en.wikipedia.org/wiki/Olivier_Panis
44,pantano,PAN,Giorgio,Pantano,1979-02-04,Italian,http://en.wikipedia.org/wiki/Giorgio_Pantano
45,bruni,BRU,Gianmaria,Bruni,1981-05-30,Italian,http://en.wikipedia.org/wiki/Gianmaria_Bruni
46,baumgartner,BAU,Zsolt,Baumgartner,1981-01-01,Hungarian,http://en.wikipedia.org/wiki/Zsolt_Baumgartner
47,gene,GEN,Marc,Gené,1974-03-29,Spanish,http://en.wikipedia.org/wiki/Marc_Gen%C3%A9
48,frentzen,FRE,Heinz-Harald,Frentzen,1967-05-18,German,http://en.wikipedia.org/wiki/Heinz-Harald_Frentzen
49,verstappen,VER,Jos,Verstappen,1972-03-04,Dutch,http://en.wikipedia.org/wiki/Jos_Verstappen
50,wilson,WIL,Justin,Wilson,1978-07-31,British,http://en.wikipedia.org/wiki/Justin_Wilson_(racing_driver)
51,firman,FIR,Ralph,Firman,1975-05-20,Irish,http://en.wikipedia.org/wiki/Ralph_Firman
52,kiesa,KIE,Nicolas,Kiesa,1978-03-03,Danish,http://en.wikipedia.org/wiki/Nicolas_Kiesa
53,burti,BUR,Luciano,Burti,1975-03-05,Brazilian,http://en.wikipedia.org/wiki/Luciano_Burti
54,alesi,ALE,Jean,Alesi,1964-06-11,French,http://en.wikipedia.org/wiki/Jean_Alesi
55,irvine,IRV,Eddie,Irvine,1965-11-10,British,http://en.wikipedia.org/wiki/Eddie_Irvine
56,hakkinen,HÄK,Mika,Häkkinen,1968-09-28,Finnish,http://en.wikipedia.org/wiki/Mika_H%C3%A4kkinen
57,marques,MAR,Tarso,Marques,1976-01-19,Brazilian,http://en.wikipedia.org/wiki/Tarso_Marques
58,bernoldi,BER,Enrique,Bernoldi,1978-10-19,Brazilian,http://en.wikipedia.org/wiki/Enrique_Bernoldi
59,mazzacane,MAZ,Gastón,Mazzacane,1975-05-08,Argentine,http://en.wikipedia.org/wiki/Gast%C3%B3n_Mazzacane
60,enge,ENG,Tomáš,Enge,1976-09-11,Czech,http://en.wikipedia.org/wiki/Tom%C3%A1%C5%A1_Enge
61,yoong,YOO,Alex,Yoong,1976-07-20,Malaysian,http://en.wikipedia.org/wiki/Alex_Yoong
62,salo,SAL,Mika,Salo,1966-11-30,Finnish,http://en.wikipedia.org/wiki/Mika_Salo
63,diniz,DIN,Pedro,Diniz,1970-05-22,Brazilian,http://en.wikipedia.org/wiki/Pedro_Diniz
64,herbert,HER,Johnny,Herbert,1964-06-25,British,http://en.wikipedia.org/wiki/Johnny_Herbert
65,mcnish,MCN,Allan,McNish,1969-12-29,British,http://en.wikipedia.org/wiki/Allan_McNish
66,buemi,BUE,Sébastien,Buemi,1988-10-31,Swiss,http://en.wikipedia.org/wiki/S%C3%A9bastien_Buemi
67,takagi,TAK,Toranosuke,Takagi,1974-02-12,Japanese,http://en.wikipedia.org/wiki/Toranosuke_Takagi
68,badoer,BAD,Luca,Badoer,1971-01-25,Italian,http://en.wikipedia.org/wiki/Luca_Badoer
69,zanardi,ZAN,Alessandro,Zanardi,1966-10-23,Italian,http://en.wikipedia.org/wiki/Alex_Zanardi
70,damon_hill,HIL,Damon,Hill,1960-09-17,British,http://en.wikipedia.org/wiki/Damon_Hill
71,sarrazin,SAR,Stéphane,Sarrazin,1975-11-02,French,http://en.wikipedia.org/wiki/St%C3%A9phane_Sarrazin
72,rosset,ROS,Ricardo,Rosset,1968-07-27,Brazilian,http://en.wikipedia.org/wiki/Ricardo_Rosset
73,tuero,TUE,Esteban,Tuero,1978-04-22,Argentine,http://en.wikipedia.org/wiki/Esteban_Tuero
74,nakano,NAK,Shinji,Nakano,1971-04-01,Japanese,http://en.wikipedia.org/wiki/Shinji_Nakano
75,magnussen,MAG,Jan,Magnussen,1973-07-04,Danish,http://en.wikipedia.org/wiki/Jan_Magnussen
76,berger,BER,Gerhard,Berger,1959-08-27,Austrian,http://en.wikipedia.org/wiki/Gerhard_Berger
77,larini,LAR,Nicola,Larini,1964-03-19,Italian,http://en.wikipedia.org/wiki/Nicola_Larini
78,katayama,KAT,Ukyo,Katayama,1963-05-29,Japanese,http://en.wikipedia.org/wiki/Ukyo_Katayama
79,sospiri,SOS,Vincenzo,Sospiri,1966-10-07,Italian,http://en.wikipedia.org/wiki/Vincenzo_Sospiri
80,morbidelli,MOR,Gianni,Morbidelli,1968-01-13,Italian,http://en.wikipedia.org/wiki/Gianni_Morbidelli
81,fontana,FON,Norberto,Fontana,1975-01-20,Argentine,http://en.wikipedia.org/wiki/Norberto_Fontana
82,lamy,LAM,Pedro,Lamy,1972-03-20,Portuguese,http://en.wikipedia.org/wiki/Pedro_Lamy
83,brundle,BRU,Martin,Brundle,1959-06-01,British,http://en.wikipedia.org/wiki/Martin_Brundle
84,montermini,MON,Andrea,Montermini,1964-05-30,Italian,http://en.wikipedia.org/wiki/Andrea_Montermini
85,lavaggi,LAV,Giovanni,Lavaggi,1958-02-18,Italian,http://en.wikipedia.org/wiki/Giovanni_Lavaggi
86,blundell,BLU,Mark,Blundell,1966-04-08,British,http://en.wikipedia.org/wiki/Mark_Blundell
87,suzuki,SUZ,Aguri,Suzuki,1960-09-08,Japanese,http://en.wikipedia.org/wiki/Aguri_Suzuki
88,inoue,INO,Taki,Inoue,1963-09-05,Japanese,http://en.wikipedia.org/wiki/Taki_Inoue
89,moreno,MOR,Roberto,Moreno,1959-02-11,Brazilian,http://en.wikipedia.org/wiki/Roberto_Moreno
90,wendlinger,WEN,Karl,Wendlinger,1968-12-20,Austrian,http://en.wikipedia.org/wiki/Karl_Wendlinger
91,gachot,GAC,Bertrand,Gachot,1962-12-23,Belgian,http://en.wikipedia.org/wiki/Bertrand_Gachot
92,schiattarella,SCH,Domenico,Schiattarella,1967-11-17,Italian,http://en.wikipedia.org/wiki/Domenico_Schiattarella
93,martini,MAR,Pierluigi,Martini,1961-04-23,Italian,http://en.wikipedia.org/wiki/Pierluigi_Martini
94,mansell,MAN,Nigel,Mansell,1953-08-08,British,http://en.wikipedia.org/wiki/Nigel_Mansell
95,boullion,BOU,Jean-Christophe,Boullion,1969-12-27,French,http://en.wikipedia.org/wiki/Jean-Christophe_Boullion
96,papis,PAP,Massimiliano,Papis,1969-10-03,Italian,http://en.wikipedia.org/wiki/Massimiliano_Papis
97,deletraz,DÉL,Jean-Denis,Délétraz,1963-10-01,Swiss,http://en.wikipedia.org/wiki/Jean-Denis_Deletraz
98,tarquini,TAR,Gabriele,Tarquini,1962-03-02,Italian,http://en.wikipedia.org/wiki/Gabriele_Tarquini
99,comas,COM,Érik,Comas,1963-09-28,French,http://en.wikipedia.org/wiki/%C3%89rik_Comas
100,brabham,BRA,David,Brabham,1965-09-05,Australian,http://en.wikipedia.org/wiki/David_Brabham
101,senna,SEN,Ayrton,Senna,1960-03-21,Brazilian,http://en.wikipedia.org/wiki/Ayrton_Senna
102,bernard,BER,Éric,Bernard,1964-08-24,French,http://en.wikipedia.org/wiki/%C3%89ric_Bernard
103,fittipaldi,FIT,Christian,Fittipaldi,1971-01-18,Brazilian,http://en.wikipedia.org/wiki/Christian_Fittipaldi
104,alboreto,ALB,Michele,Alboreto,1956-12-23,Italian,http://en.wikipedia.org/wiki/Michele_Alboreto
105,beretta,BER,Olivier,Beretta,1969-11-23,Monegasque,http://en.wikipedia.org/wiki/Olivier_Beretta
106,ratzenberger,RAT,Roland,Ratzenberger,1960-07-04,Austrian,http://en.wikipedia.org/wiki/Roland_Ratzenberger
107,belmondo,BEL,Paul,Belmondo,1963-04-23,French,http://en.wikipedia.org/wiki/Paul_Belmondo
108,lehto,JÄR,Jyrki,Järvilehto,1966-01-31,Finnish,http://en.wikipedia.org/wiki/Jyrki_J%C3%A4rvilehto
109,cesaris,DEC,Andrea,de Cesaris,1959-05-31,Italian,http://en.wikipedia.org/wiki/Andrea_de_Cesaris
110,gounon,GOU,Jean-Marc,Gounon,1963-01-01,French,http://en.wikipedia.org/wiki/Jean-Marc_Gounon
111,alliot,ALL,Philippe,Alliot,1954-07-27,French,http://en.wikipedia.org/wiki/Philippe_Alliot
112,adams,ADA,Philippe,Adams,1969-11-19,Belgian,http://en.wikipedia.org/wiki/Philippe_Adams
113,dalmas,DAL,Yannick,Dalmas,1961-07-28,French,http://en.wikipedia.org/wiki/Yannick_Dalmas
114,noda,NOD,Hideki,Noda,1969-03-07,Japanese,http://en.wikipedia.org/wiki/Hideki_Noda
115,lagorce,LAG,Franck,Lagorce,1968-09-01,French,http://en.wikipedia.org/wiki/Franck_Lagorce
116,prost,PRO,Alain,Prost,1955-02-24,French,http://en.wikipedia.org/wiki/Alain_Prost
117,warwick,WAR,Derek,Warwick,1954-08-27,British,http://en.wikipedia.org/wiki/Derek_Warwick
118,patrese,PAT,Riccardo,Patrese,1954-04-17,Italian,http://en.wikipedia.org/wiki/Riccardo_Patrese
119,barbazza,BAR,Fabrizio,Barbazza,1963-04-02,Italian,http://en.wikipedia.org/wiki/Fabrizio_Barbazza
120,andretti,AND,Michael,Andretti,1962-10-05,American,http://en.wikipedia.org/wiki/Michael_Andretti
121,capelli,CAP,Ivan,Capelli,1963-05-24,Italian,http://en.wikipedia.org/wiki/Ivan_Capelli
122,boutsen,BOU,Thierry,Boutsen,1957-07-13,Belgian,http://en.wikipedia.org/wiki/Thierry_Boutsen
123,apicella,API,Marco,Apicella,1965-10-07,Italian,http://en.wikipedia.org/wiki/Marco_Apicella
124,naspetti,NAS,Emanuele,Naspetti,1968-02-24,Italian,http://en.wikipedia.org/wiki/Emanuele_Naspetti
125,toshio_suzuki,SUZ,Toshio,Suzuki,1955-03-10,Japanese,http://en.wikipedia.org/wiki/Toshio_Suzuki_(driver)
126,gugelmin,GUG,Maurício,Gugelmin,1963-04-20,Brazilian,http://en.wikipedia.org/wiki/Maur%C3%ADcio_Gugelmin
127,poele,VAN,Eric,van de Poele,1961-09-30,Belgian,http://en.wikipedia.org/wiki/Eric_van_de_Poele
128,grouillard,GRO,Olivier,Grouillard,1958-09-02,French,http://en.wikipedia.org/wiki/Olivier_Grouillard
129,chiesa,CHI,Andrea,Chiesa,1964-05-06,Swiss,http://en.wikipedia.org/wiki/Andrea_Chiesa
130,modena,MOD,Stefano,Modena,1963-05-12,Italian,http://en.wikipedia.org/wiki/Stefano_Modena
131,amati,AMA,Giovanna,Amati,1959-07-20,Italian,http://en.wikipedia.org/wiki/Giovanna_Amati
132,caffi,CAF,Alex,Caffi,1964-03-18,Italian,http://en.wikipedia.org/wiki/Alex_Caffi
133,bertaggia,BER,Enrico,Bertaggia,1964-09-19,Italian,http://en.wikipedia.org/wiki/Enrico_Bertaggia
134,mccarthy,MCC,Perry,McCarthy,1961-03-03,British,http://en.wikipedia.org/wiki/Perry_McCarthy
135,lammers,LAM,Jan,Lammers,1956-06-02,Dutch,http://en.wikipedia.org/wiki/Jan_Lammers
136,piquet,PIQ,Nelson,Piquet,1952-08-17,Brazilian,http://en.wikipedia.org/wiki/Nelson_Piquet
137,satoru_nakajima,NAK,Satoru,Nakajima,1953-02-23,Japanese,http://en.wikipedia.org/wiki/Satoru_Nakajima
138,pirro,PIR,Emanuele,Pirro,1962-01-12,Italian,http://en.wikipedia.org/wiki/Emanuele_Pirro
139,johansson,JOH,Stefan,Johansson,1956-09-08,Swedish,http://en.wikipedia.org/wiki/Stefan_Johansson
140,bailey,BAI,Julian,Bailey,1961-10-09,British,http://en.wikipedia.org/wiki/Julian_Bailey
141,chaves,CHA,Pedro,Chaves,1965-02-27,Portuguese,http://en.wikipedia.org/wiki/Pedro_Chaves
142,bartels,BAR,Michael,Bartels,1968-03-08,German,http://en.wikipedia.org/wiki/Michael_Bartels
143,hattori,HAT,Naoki,Hattori,1966-06-13,Japanese,http://en.wikipedia.org/wiki/Naoki_Hattori
144,nannini,NAN,Alessandro,Nannini,1959-07-07,Italian,http://en.wikipedia.org/wiki/Alessandro_Nannini
145,schneider,SCH,Bernd,Schneider,1964-07-20,German,http://en.wikipedia.org/wiki/Bernd_Schneider_(racecar_driver)
146,barilla,BAR,Paolo,Barilla,1961-04-20,Italian,http://en.wikipedia.org/wiki/Paolo_Barilla
147,foitek,FOI,Gregor,Foitek,1965-03-27,Swiss,http://en.wikipedia.org/wiki/Gregor_Foitek
148,langes,LAN,Claudio,Langes,1960-07-20,Italian,http://en.wikipedia.org/wiki/Claudio_Langes
149,gary_brabham,BRA,Gary,Brabham,1961-03-29,Australian,http://en.wikipedia.org/wiki/Gary_Brabham
150,donnelly,DON,Martin,Donnelly,1964-03-26,British,http://en.wikipedia.org/wiki/Martin_Donnelly_(racing_driver)
151,giacomelli,GIA,Bruno,Giacomelli,1952-09-10,Italian,http://en.wikipedia.org/wiki/Bruno_Giacomelli
152,alguersuari,ALG,Jaime,Alguersuari,1990-03-23,Spanish,http://en.wikipedia.org/wiki/Jaime_Alguersuari
153,grosjean,GRO,Romain,Grosjean,1986-04-17,French,http://en.wikipedia.org/wiki/Romain_Grosjean
154,kobayashi,KOB,Kamui,Kobayashi,1986-09-13,Japanese,http://en.wikipedia.org/wiki/Kamui_Kobayashi
155,palmer,PAL,Jonathan,Palmer,1956-11-07,British,http://en.wikipedia.org/wiki/Jonathan_Palmer
156,danner,DAN,Christian,Danner,1958-04-04,German,http://en.wikipedia.org/wiki/Christian_Danner
157,cheever,CHE,Eddie,Cheever,1958-01-10,American,http://en.wikipedia.org/wiki/Eddie_Cheever
158,sala,PÉR,Luis,Pérez-Sala,1959-05-15,Spanish,http://en.wikipedia.org/wiki/Luis_Perez-Sala
159,ghinzani,GHI,Piercarlo,Ghinzani,1952-01-16,Italian,http://en.wikipedia.org/wiki/Piercarlo_Ghinzani
160,weidler,WEI,Volker,Weidler,1962-03-18,German,http://en.wikipedia.org/wiki/Volker_Weidler
161,raphanel,RAP,Pierre-Henri,Raphanel,1961-05-27,French,http://en.wikipedia.org/wiki/Pierre-Henri_Raphanel
162,arnoux,ARN,René,Arnoux,1948-07-04,French,http://en.wikipedia.org/wiki/Ren%C3%A9_Arnoux
163,joachim_winkelhock,WIN,Joachim,Winkelhock,1960-10-24,German,http://en.wikipedia.org/wiki/Joachim_Winkelhock
164,larrauri,LAR,Oscar,Larrauri,1954-08-19,Argentine,http://en.wikipedia.org/wiki/Oscar_Larrauri
165,streiff,STR,Philippe,Streiff,1955-06-26,French,http://en.wikipedia.org/wiki/Philippe_Streiff
166,campos,CAM,Adrián,Campos,1960-06-17,Spanish,http://en.wikipedia.org/wiki/Adri%C3%A1n_Campos
167,schlesser,SCH,Jean-Louis,Schlesser,1948-09-12,French,http://en.wikipedia.org/wiki/Jean-Louis_Schlesser
168,fabre,FAB,Pascal,Fabre,1960-01-09,French,http://en.wikipedia.org/wiki/Pascal_Fabre
169,fabi,FAB,Teo,Fabi,1955-03-09,Italian,http://en.wikipedia.org/wiki/Teo_Fabi
170,forini,FOR,Franco,Forini,1958-09-22,Swiss,http://en.wikipedia.org/wiki/Franco_Forini
171,laffite,LAF,Jacques,Laffite,1943-11-21,French,http://en.wikipedia.org/wiki/Jacques_Laffite
172,angelis,DEA,Elio,de Angelis,1958-03-26,Italian,http://en.wikipedia.org/wiki/Elio_de_Angelis
173,dumfries,DUM,Johnny,Dumfries,1958-04-26,British,http://en.wikipedia.org/wiki/Johnny_Dumfries
174,tambay,TAM,Patrick,Tambay,1949-06-25,French,http://en.wikipedia.org/wiki/Patrick_Tambay
175,surer,SUR,Marc,Surer,1951-09-18,Swiss,http://en.wikipedia.org/wiki/Marc_Surer
176,keke_rosberg,ROS,Keke,Rosberg,1948-12-06,Finnish,http://en.wikipedia.org/wiki/Keke_Rosberg
177,jones,JON,Alan,Jones,1946-11-02,Australian,http://en.wikipedia.org/wiki/Alan_Jones_(Formula_1)
178,rothengatter,ROT,Huub,Rothengatter,1954-10-08,Dutch,http://en.wikipedia.org/wiki/Huub_Rothengatter
179,berg,BER,Allen,Berg,1961-08-01,Canadian,http://en.wikipedia.org/wiki/Allen_Berg
180,manfred_winkelhock,WIN,Manfred,Winkelhock,1951-10-06,German,http://en.wikipedia.org/wiki/Manfred_Winkelhock
181,lauda,LAU,Niki,Lauda,1949-02-22,Austrian,http://en.wikipedia.org/wiki/Niki_Lauda
182,hesnault,HES,François,Hesnault,1956-12-30,French,http://en.wikipedia.org/wiki/Fran%C3%A7ois_Hesnault
183,baldi,BAL,Mauro,Baldi,1954-01-31,Italian,http://en.wikipedia.org/wiki/Mauro_Baldi
184,bellof,BEL,Stefan,Bellof,1957-11-20,German,http://en.wikipedia.org/wiki/Stefan_Bellof
185,acheson,ACH,Kenny,Acheson,1957-11-27,British,http://en.wikipedia.org/wiki/Kenny_Acheson
186,watson,WAT,John,Watson,1946-05-04,British,http://en.wikipedia.org/wiki/John_Watson_(racing_driver)
187,cecotto,CEC,Johnny,Cecotto,1956-01-25,Venezuelan,http://en.wikipedia.org/wiki/Johnny_Cecotto
188,gartner,GAR,Jo,Gartner,1954-01-24,Austrian,http://en.wikipedia.org/wiki/Jo_Gartner
189,corrado_fabi,FAB,Corrado,Fabi,1961-04-12,Italian,http://en.wikipedia.org/wiki/Corrado_Fabi
190,thackwell,THA,Mike,Thackwell,1961-03-30,New Zealander,http://en.wikipedia.org/wiki/Mike_Thackwell
191,serra,SER,Chico,Serra,1957-02-03,Brazilian,http://en.wikipedia.org/wiki/Chico_Serra
192,sullivan,SUL,Danny,Sullivan,1950-03-09,American,http://en.wikipedia.org/wiki/Danny_Sullivan
193,salazar,SAL,Eliseo,Salazar,1954-11-14,Chilean,http://en.wikipedia.org/wiki/Eliseo_Salazar
194,guerrero,GUE,Roberto,Guerrero,1958-11-16,Colombian,http://en.wikipedia.org/wiki/Roberto_Guerrero
195,boesel,BOE,Raul,Boesel,1957-12-04,Brazilian,http://en.wikipedia.org/wiki/Raul_Boesel
196,jarier,JAR,Jean-Pierre,Jarier,1946-07-10,French,http://en.wikipedia.org/wiki/Jean-Pierre_Jarier
197,villeneuve_sr,VIL,Jacques,Villeneuve Sr.,1953-11-04,Canadian,http://en.wikipedia.org/wiki/Jacques_Villeneuve_(elder)
198,reutemann,REU,Carlos,Reutemann,1942-04-12,Argentine,http://en.wikipedia.org/wiki/Carlos_Reutemann
199,mass,MAS,Jochen,Mass,1946-09-30,German,http://en.wikipedia.org/wiki/Jochen_Mass
200,borgudd,BOR,Slim,Borgudd,1946-11-25,Swedish,http://en.wikipedia.org/wiki/Slim_Borgudd
201,pironi,PIR,Didier,Pironi,1952-03-26,French,http://en.wikipedia.org/wiki/Didier_Pironi
202,gilles_villeneuve,VIL,Gilles,Villeneuve,1950-01-18,Canadian,http://en.wikipedia.org/wiki/Gilles_Villeneuve
203,paletti,PAL,Riccardo,Paletti,1958-06-15,Italian,http://en.wikipedia.org/wiki/Riccardo_Paletti
204,henton,HEN,Brian,Henton,1946-09-19,British,http://en.wikipedia.org/wiki/Brian_Henton
205,daly,DAL,Derek,Daly,1953-03-11,Irish,http://en.wikipedia.org/wiki/Derek_Daly
206,mario_andretti,AND,Mario,Andretti,1940-02-28,American,http://en.wikipedia.org/wiki/Mario_Andretti
207,villota,DEV,Emilio,de Villota,1946-07-26,Spanish,http://en.wikipedia.org/wiki/Emilio_de_Villota

In [6]:
drivers_updated_c

,Driver_ID,Driver,Nationality,Car,PTS,year,Code,Final_Pos
0,1,Nino Farina,ITA,Alfa Romeo,30.0,1950,FAR,1
1,2,Juan Manuel Fangio,ARG,Alfa Romeo,27.0,1950,FAN,2
2,3,Luigi Fagioli,ITA,Alfa Romeo,24.0,1950,FAG,3
3,4,Louis Rosier,FRA,Talbot-Lago,13.0,1950,ROS,4
4,5,Alberto Ascari,ITA,Ferrari,11.0,1950,ASC,5
5,6,Johnnie Parsons,USA,Kurtis Kraft Offenhauser,9.0,1950,PAR,6
6,7,Bill Holland,USA,Deidt Offenhauser,6.0,1950,HOL,7
7,8,Prince Bira,THA,Maserati,5.0,1950,BIR,8
8,9,Reg Parnell,GBR,Maserati,4.0,1950,PAR,9
9,10,Louis Chiron,MON,Maserati,4.0,1950,CHI,9
10,11,Mauri Rose,USA,Deidt Offenhauser,4.0,1950,ROS,9
11,12,Peter Whitehead,GBR,Ferrari,4.0,1950,WHI,9
12,13,Yves Giraud Cabantous,FRA,Talbot-Lago,3.0,1950,CAB,13
13,14,Raymond Sommer,FRA,Talbot-Lago,3.0,1950,SOM,13
14,15,Cecil Green,USA,Kurtis Kraft Offenhauser,3.0,1950,GRE,13
15,16,Robert Manzon,FRA,Simca-Gordini,3.0,1950,MAN,13
16,17,Dorino Serafini,ITA,NaN,3.0,1950,SER,13
17,18,Philippe Etancelin,FRA,NaN,3.0,1950,ETA,13
18,19,Felice Bonetto,ITA,Maserati Milano,2.0,1950,BON,19
19,20,Tony Bettenhausen,USA,Deidt Offenhauser,1.0,1950,BET,20
20,21,Joie Chitwood,USA,Kurtis Kraft Offenhauser,1.0,1950,CHI,20
21,22,Eugene Chaboud,FRA,NaN,1.0,1950,CHA,20
22,23,Juan Manuel Fangio,ARG,Alfa Romeo,31.0,1951,FAN,1
23,24,Alberto Ascari,ITA,Ferrari,25.0,1951,ASC,2
24,25,Jose Froilan Gonzalez,ARG,Ferrari,24.0,1951,GON,3
25,26,Nino Farina,ITA,Alfa Romeo,19.0,1951,FAR,4
26,27,Luigi Villoresi,ITA,Ferrari,15.0,1951,VIL,5
27,28,Piero Taruffi,ITA,Ferrari,10.0,1951,TAR,6
28,29,Lee Wallard,USA,Kurtis Kraft Offenhauser,9.0,1951,WAL,7
29,30,Felice Bonetto,ITA,Alfa Romeo,7.0,1951,BON,8
30,31,Mike Nazaruk,USA,Kurtis Kraft Offenhauser,6.0,1951,NAZ,9
31,32,Reg Parnell,GBR,BRM,5.0,1951,PAR,10
32,33,Luigi Fagioli,ITA,Alfa Romeo,4.0,1951,FAG,11
33,34,Consalvo Sanesi,ITA,Alfa Romeo,3.0,1951,SAN,12
34,35,Andy Linden,USA,Sherman Offenhauser,3.0,1951,LIN,12
35,36,Louis Rosier,FRA,NaN,3.0,1951,ROS,12
36,37,Toulo de Graffenried,SUI,Alfa Romeo,2.0,1951,DEG,15
37,38,Manny Ayulo,USA,Kurtis Kraft Offenhauser,2.0,1951,AYU,15
38,39,Bobby Ball,USA,Schroeder Offenhauser,2.0,1951,BAL,15
39,40,Jack McGrath,USA,Kurtis Kraft Offenhauser,2.0,1951,MCG,15
40,41,Yves Giraud Cabantous,FRA,Talbot-Lago,2.0,1951,CAB,15
41,42,Alberto Ascari,ITA,Ferrari,36.0,1952,ASC,1
42,43,Nino Farina,ITA,Ferrari,24.0,1952,FAR,2
43,44,Piero Taruffi,ITA,Ferrari,22.0,1952,TAR,3
44,45,Rudi Fischer,SUI,Ferrari,10.0,1952,FIS,4
45,46,Mike Hawthorn,GBR,Cooper Bristol,10.0,1952,HAW,4
46,47,Robert Manzon,FRA,Gordini,9.0,1952,MAN,6
47,48,Troy Ruttman,USA,Kuzma Offenhauser,8.0,1952,RUT,7
48,49,Luigi Villoresi,ITA,Ferrari,8.0,1952,VIL,7
49,50,Jose Froilan Gonzalez,ARG,Maserati,6.5,1952,GON,9
50,51,Jim Rathmann,USA,Kurtis Kraft Offenhauser,6.0,1952,RAT,10
51,52,Jean Behra,FRA,Gordini,6.0,1952,BEH,10
52,53,Sam Hanks,USA,Kurtis Kraft Offenhauser,4.0,1952,HAN,12
53,54,Ken Wharton,GBR,NaN,3.0,1952,WHA,13
54,55,Duane Carter,USA,Lesovsky Offenhauser,3.0,1952,CAR,13
55,56,Dennis Poore,GBR,Connaught Lea Francis,3.0,1952,POO,13
56,57,Alan Brown,GBR,Cooper Bristol,2.0,1952,BRO,16
57,58,Art Cross,USA,Kurtis Kraft Offenhauser,2.0,1952,CRO,16
58,59,Paul Frere,BEL,Simca-Gordini,2.0,1952,FRE,16
59,60,Maurice Trintignant,FRA,Gordini,2.0,1952,TRI,16
60,61,Eric Thompson,GBR,Connaught Lea Francis,2.0,1952,THO,16
61,62,Felice Bonetto,ITA,Maserati,2.0,1952,BON,16
62,63,Bill Vukovich,USA,Kurtis Kraft Offenhauser,1.0,1952,VUK,22
63,64,Alberto Ascari,ITA,Ferrari,34.5,1953,ASC,1
64,65,Juan Manuel Fangio,ARG,Maserati,27.5,1953,FAN,2
65,66,Nino Farina,ITA,Ferrari,26.0,1953,FAR,3
66,67,Mike Hawthorn,GBR,Ferrari,19.0,1953,HAW,4
67,68,Luigi Villoresi,ITA,Ferrari,17.0,1953,VIL,5
68,69,Jose Froilan Gonzalez,ARG,Maserati,13.5,1953,GON,6
69,70,Bill Vukovich,USA,Kurtis Kraft Offenhauser,9.0,1953,VUK,7
70,71,Toulo de Graffenried,SUI,Maserati,7.0,1953,DEG,8
71,72,Felice Bonetto,ITA,Maserati,6.5,1953,BON,9
72,73,Art Cross,USA,Kurtis Kraft Offenhauser,6.0,1953,CRO,10
73,74,Onofre Marimon,ARG,Maserati,4.0,1953,MAR,11
74,75,Maurice Trintignant,FRA,Gordini,4.0,1953,TRI,11
75,76,Oscar Alfredo Galvez,ARG,Maserati,2.0,1953,GAL,13
76,77,Sam Hanks,USA,Kurtis Kraft Offenhauser,2.0,1953,HAN,13
77,78,Duane Carter,USA,Kurtis Kraft Offenhauser,2.0,1953,CAR,13
78,79,Jack McGrath,USA,Kurtis Kraft Offenhauser,2.0,1953,MCG,13
79,80,Hermann Lang,GER,Maserati,2.0,1953,LAN,13
80,81,Fred Agabashian,USA,Kurtis Kraft Offenhauser,1.5,1953,AGA,18
81,82,Paul Russo,USA,Kurtis Kraft Offenhauser,1.5,1953,RUS,18
82,83,Juan Manuel Fangio,ARG,Mercedes-Benz,42.0,1954,FAN,1
83,84,Jose Froilan Gonzalez,ARG,Ferrari,25.1,1954,GON,2
84,85,Mike Hawthorn,GBR,Ferrari,24.6,1954,HAW,3
85,86,Maurice Trintignant,FRA,Ferrari,17.0,1954,TRI,4
86,87,Karl Kling,GER,Mercedes-Benz,12.0,1954,KLI,5
87,88,Bill Vukovich,USA,Kurtis Kraft Offenhauser,8.0,1954,VUK,6
88,89,Hans Herrmann,GER,Mercedes-Benz,8.0,1954,HER,6
89,90,Nino Farina,ITA,Ferrari,6.0,1954,FAR,8
90,91,Jimmy Bryan,USA,Kuzma Offenhauser,6.0,1954,BRY,8
91,92,Luigi Musso,ITA,Maserati,6.0,1954,MUS,8
92,93,Roberto Mieres,ARG,Maserati,6.0,1954,MIE,8
93,94,Jack McGrath,USA,Kurtis Kraft Offenhauser,5.0,1954,MCG,12
94,95,Stirling Moss,GBR,Maserati,4.1,1954,MOS,13
95,96,Onofre Marimon,ARG,Maserati,4.1,1954,MAR,13
96,97,Robert Manzon,FRA,Ferrari,4.0,1954,MAN,15
97,98,Sergio Mantovani,ITA,Maserati,4.0,1954,MAN,15
98,99,Prince Bira,THA,Maserati,3.0,1954,BIR,17
99,100,Elie Bayol,FRA,Gordini,2.0,1954,BAY,18
100,101,Mike Nazaruk,USA,Kurtis Kraft Offenhauser,2.0,1954,NAZ,18
101,102,Andre Pilette,BEL,Gordini,2.0,1954,PIL,18
102,103,Luigi Villoresi,ITA,Lancia,2.0,1954,VIL,18
103,104,Umberto Maglioli,ITA,Ferrari,2.0,1954,MAG,18
104,105,Troy Ruttman,USA,Kurtis Kraft Offenhauser,1.5,1954,RUT,23
105,106,Duane Carter,USA,Kurtis Kraft Offenhauser,1.5,1954,CAR,23
106,107,Alberto Ascari,ITA,Lancia,1.1,1954,ASC,25
107,108,Jean Behra,FRA,Gordini,0.1,1954,BEH,26
108,109,Juan Manuel Fangio,ARG,Mercedes-Benz,40.0,1955,FAN,1
109,110,Stirling Moss,GBR,Mercedes-Benz,23.0,1955,MOS,2
110,111,Eugenio Castellotti,ITA,Ferrari,12.0,1955,CAS,3
111,112,Maurice Trintignant,FRA,Ferrari,11.3,1955,TRI,4
112,113,Nino Farina,ITA,Ferrari,10.3,1955,FAR,5
113,114,Piero Taruffi,ITA,Mercedes-Benz,9.0,1955,TAR,6
114,115,Bob Sweikert,USA,Kurtis Kraft Offenhauser,8.0,1955,SWE,7
115,116,Roberto Mieres,ARG,Maserati,7.0,1955,MIE,8
116,117,Luigi Musso,ITA,Maserati,6.0,1955,MUS,9
117,118,Jean Behra,FRA,Maserati,6.0,1955,BEH,9
118,119,Karl Kling,GER,Mercedes-Benz,5.0,1955,KLI,11
119,120,Jimmy Davies,USA,Kurtis Kraft Offenhauser,4.0,1955,DAV,12
120,121,Paul Russo,USA,Kurtis Kraft Offenhauser,3.0,1955,RUS,13
121,122,Tony Bettenhausen,USA,Kurtis Kraft Offenhauser,3.0,1955,BET,13
122,123,Johnny Thomson,USA,Kuzma Offenhauser,3.0,1955,THO,13
123,124,Paul Frere,BEL,Ferrari,3.0,1955,FRE,13
124,125,Jose Froilan Gonzalez,ARG,Ferrari,2.0,1955,GON,17
125,126,Cesare Perdisa,ITA,Maserati,2.0,1955,PER,17
126,127,Luigi Villoresi,ITA,Lancia,2.0,1955,VIL,17
127,128,Carlos Menditeguy,ARG,Maserati,2.0,1955,MEN,17
128,129,Umberto Maglioli,ITA,Ferrari,1.3,1955,MAG,21
129,130,Hans Herrmann,GER,Mercedes-Benz,1.0,1955,HER,22
130,131,Walt Faulkner,USA,Kurtis Kraft Offenhauser,1.0,1955,FAU,22
131,132,Bill Homeier,USA,Kurtis Kraft Offenhauser,1.0,1955,HOM,22
132,133,Bill Vukovich,USA,Kurtis Kraft Offenhauser,1.0,1955,VUK,22
133,134,Juan Manuel Fangio,ARG,Ferrari,30.0,1956,FAN,1
134,135,Stirling Moss,GBR,Maserati,27.0,1956,MOS,2
135,136,Peter Collins,GBR,Ferrari,25.0,1956,COL,3
136,137,Jean Behra,FRA,Maserati,22.0,1956,BEH,4
137,138,Pat Flaherty,USA,Watson Offenhauser,8.0,1956,FLA,5
138,139,Eugenio Castellotti,ITA,Ferrari,7.5,1956,CAS,6
139,140,Sam Hanks,USA,Kurtis Kraft Offenhauser,6.0,1956,HAN,7
140,141,Paul Frere,BEL,Ferrari,6.0,1956,FRE,7
141,142,Paco Godia,ESP,Maserati,6.0,1956,GOD,7
142,143,Jack Fairman,GBR,Connaught Alta,5.0,1956,FAI,10
143,144,Mike Hawthorn,GBR,BRM,4.0,1956,HAW,11
144,145,Luigi Musso,ITA,Ferrari,4.0,1956,MUS,11
145,146,Don Freeland,USA,Phillips Offenhauser,4.0,1956,FRE,11
146,147,Ron Flockhart,GBR,Connaught Alta,4.0,1956,FLO,11
147,148,Johnnie Parsons,USA,Kuzma Offenhauser,3.0,1956,PAR,15
148,149,Harry Schell,USA,Vanwall,3.0,1956,SCH,15
149,150,Alfonso de Portago,ESP,Ferrari,3.0,1956,DEP,15
150,151,Cesare Perdisa,ITA,Maserati,3.0,1956,PER,15
151,152,Olivier Gendebien,BEL,Ferrari,2.0,1956,GEN,19
152,153,Hermano da Silva Ramos,BRA,Gordini,2.0,1956,DAS,19
153,154,Dick Rathmann,USA,Kurtis Kraft Offenhauser,2.0,1956,RAT,19
154,155,Luigi Villoresi,ITA,Maserati,2.0,1956,VIL,19
155,156,Horace Gould,GBR,Maserati,2.0,1956,GOU,19
156,157,Louis Rosier,FRA,Maserati,2.0,1956,ROS,19
157,158,Gerino Gerini,ITA,Maserati,1.5,1956,GER,25
158,159,Chico Landi,BRA,Maserati,1.5,1956,LAN,25
159,160,Paul Russo,USA,Kurtis Kraft Novi,1.0,1956,RUS,27
160,161,Juan Manuel Fangio,ARG,Maserati,40.0,1957,FAN,1
161,162,Stirling Moss,GBR,Vanwall,25.0,1957,MOS,2
162,163,Luigi Musso,ITA,Ferrari,16.0,1957,MUS,3
163,164,Mike Hawthorn,GBR,Ferrari,13.0,1957,HAW,4
164,165,Tony Brooks,GBR,Vanwall,11.0,1957,BRO,5
165,166,Masten Gregory,USA,Maserati,10.0,1957,GRE,6
166,167,Harry Schell,USA,Maserati,10.0,1957,SCH,6
167,168,Sam Hanks,USA,Epperly Offenhauser,8.0,1957,HAN,8
168,169,Peter Collins,GBR,Ferrari,8.0,1957,COL,8
169,170,Jim Rathmann,USA,Epperly Offenhauser,7.0,1957,RAT,10
170,171,Jean Behra,FRA,Maserati,6.0,1957,BEH,11
171,172,Stuart Lewis-Evans,GBR,Vanwall,5.0,1957,LEW,12
172,173,Maurice Trintignant,FRA,Ferrari,5.0,1957,TRI,12
173,174,Carlos Menditeguy,ARG,Maserati,4.0,1957,MEN,14
174,175,Jimmy Bryan,USA,Kuzma Offenhauser,4.0,1957,BRY,14
175,176,Wolfgang von Trips,GER,Ferrari,4.0,1957,VON,14
176,177,Paul Russo,USA,Kurtis Kraft Novi,3.0,1957,RUS,17
177,178,Andy Linden,USA,Kurtis Kraft Offenhauser,2.0,1957,LIN,18
178,179,Roy Salvadori,GBR,Cooper Climax,2.0,1957,SAL,18
179,180,Alfonso de Portago,ESP,Ferrari,1.0,1957,DEP,20
180,181,Jose Froilan Gonzalez,ARG,Ferrari,1.0,1957,GON,20
181,182,Giorgio Scarlatti,ITA,Maserati,1.0,1957,SCA,20
182,183,Mike Hawthorn,GBR,Ferrari,42.0,1958,HAW,1
183,184,Stirling Moss,GBR,Vanwall,41.0,1958,MOS,2
184,185,Tony Brooks,GBR,Vanwall,24.0,1958,BRO,3
185,186,Roy Salvadori,GBR,Cooper Climax,15.0,1958,SAL,4
186,187,Peter Collins,GBR,Ferrari,14.0,1958,COL,5
187,188,Harry Schell,USA,BRM,14.0,1958,SCH,5
188,189,Maurice Trintignant,FRA,Cooper Climax,12.0,1958,TRI,7
189,190,Luigi Musso,ITA,Ferrari,12.0,1958,MUS,7
190,191,Stuart Lewis-Evans,GBR,Vanwall,11.0,1958,LEW,9
191,192,Phil Hill,USA,Ferrari,9.0,1958,HIL,10
192,193,Jean Behra,FRA,BRM,9.0,1958,BEH,10
193,194,Wolfgang von Trips,GER,Ferrari,9.0,1958,VON,10
194,195,Jimmy Bryan,USA,Epperly Offenhauser,8.0,1958,BRY,13
195,196,Juan Manuel Fangio,ARG,Maserati,7.0,1958,FAN,14
196,197,George Amick,USA,Epperly Offenhauser,6.0,1958,AMI,15
197,198,Tony Bettenhausen,USA,Epperly Offenhauser,4.0,1958,BET,16
198,199,Johnny Boyd,USA,Kurtis Kraft Offenhauser,4.0,1958,BOY,16
199,200,Jack Brabham,AUS,Cooper Climax,3.0,1958,BRA,18
200,201,Cliff Allison,GBR,Lotus Climax,3.0,1958,ALL,18
201,202,Jo Bonnier,SWE,BRM,3.0,1958,BON,18
202,203,Jim Rathmann,USA,Epperly Offenhauser,2.0,1958,RAT,21
203,204,Jack Brabham,AUS,Cooper Climax,31.0,1959,BRA,1
204,205,Tony Brooks,GBR,Ferrari,27.0,1959,BRO,2
205,206,Stirling Moss,GBR,Cooper Climax,25.5,1959,MOS,3
206,207,Phil Hill,USA,Ferrari,20.0,1959,HIL,4
207,208,Maurice Trintignant,FRA,Cooper Climax,19.0,1959,TRI,5
208,209,Bruce McLaren,NZL,Cooper Climax,16.5,1959,MCL,6
209,210,Dan Gurney,USA,Ferrari,13.0,1959,GUR,7
210,211,Jo Bonnier,SWE,BRM,10.0,1959,BON,8
211,212,Masten Gregory,USA,Cooper Climax,10.0,1959,GRE,8
212,213,Rodger Ward,USA,Kurtis Kraft Offenhauser,8.0,1959,WAR,10
213,214,Jim Rathmann,USA,Watson Offenhauser,6.0,1959,RAT,11
214,215,Johnny Thomson,USA,Lesovsky Offenhauser,5.0,1959,THO,12
215,216,Innes Ireland,GBR,Lotus Climax,5.0,1959,IRE,12
216,217,Harry Schell,USA,Cooper Climax,5.0,1959,SCH,12
217,218,Tony Bettenhausen,USA,Epperly Offenhauser,3.0,1959,BET,15
218,219,Olivier Gendebien,BEL,Ferrari,3.0,1959,GEN,15
219,220,Paul Goldsmith,USA,Epperly Offenhauser,2.0,1959,GOL,17
220,221,Jean Behra,FRA,Ferrari,2.0,1959,BEH,17
221,222,Cliff Allison,GBR,Ferrari,2.0,1959,ALL,17
222,223,Jack Brabham,AUS,Cooper Climax,43.0,1960,BRA,1
223,224,Bruce McLaren,NZL,Cooper Climax,34.0,1960,MCL,2
224,225,Stirling Moss,GBR,Lotus Climax,19.0,1960,MOS,3
225,226,Innes Ireland,GBR,Lotus Climax,18.0,1960,IRE,4
226,227,Phil Hill,USA,Cooper Climax,16.0,1960,HIL,5
227,228,Olivier Gendebien,BEL,Cooper Climax,10.0,1960,GEN,6
228,229,Wolfgang von Trips,GER,Cooper Maserati,10.0,1960,VON,6
229,230,Jim Rathmann,USA,Watson Offenhauser,8.0,1960,RAT,8
230,231,Richie Ginther,USA,Ferrari,8.0,1960,GIN,8
231,232,Jim Clark,GBR,Lotus Climax,8.0,1960,CLA,8
232,233,Tony Brooks,GBR,Cooper Climax,7.0,1960,BRO,11
233,234,Cliff Allison,GBR,Ferrari,6.0,1960,ALL,12
234,235,Rodger Ward,USA,Watson Offenhauser,6.0,1960,WAR,12
235,236,John Surtees,GBR,Lotus Climax,6.0,1960,SUR,12
236,237,Paul Goldsmith,USA,Epperly Offenhauser,4.0,1960,GOL,15
237,238,Graham Hill,GBR,BRM,4.0,1960,HIL,15
238,239,Willy Mairesse,BEL,Ferrari,4.0,1960,MAI,15
239,240,Jo Bonnier,SWE,BRM,4.0,1960,BON,15
240,241,Carlos Menditeguy,ARG,Cooper Maserati,3.0,1960,MEN,19
241,242,Don Branson,USA,Phillips Offenhauser,3.0,1960,BRA,19
242,243,Henry Taylor,GBR,Cooper Climax,3.0,1960,TAY,19
243,244,Giulio Cabianca,ITA,Cooper Castellotti,3.0,1960,CAB,19
244,245,Johnny Thomson,USA,Lesovsky Offenhauser,2.0,1960,THO,23
245,246,Eddie Johnson,USA,Trevis Offenhauser,1.0,1960,JOH,24
246,247,Lucien Bianchi,BEL,Cooper Climax,1.0,1960,BIA,24
247,248,Ron Flockhart,GBR,Cooper Climax,1.0,1960,FLO,24
248,249,Hans Herrmann,GER,Porsche,1.0,1960,HER,24
249,250,Phil Hill,USA,Ferrari,34.0,1961,HIL,1
250,251,Wolfgang von Trips,GER,Ferrari,33.0,1961,VON,2
251,252,Stirling Moss,GBR,Lotus Climax,21.0,1961,MOS,3
252,253,Dan Gurney,USA,Porsche,21.0,1961,GUR,3
253,254,Richie Ginther,USA,Ferrari,16.0,1961,GIN,5
254,255,Innes Ireland,GBR,Lotus Climax,12.0,1961,IRE,6
255,256,Jim Clark,GBR,Lotus Climax,11.0,1961,CLA,7
256,257,Bruce McLaren,NZL,Cooper Climax,11.0,1961,MCL,7
257,258,Giancarlo Baghetti,ITA,Ferrari,9.0,1961,BAG,9
258,259,Tony Brooks,GBR,BRM Climax,6.0,1961,BRO,10
259,260,Jack Brabham,AUS,Cooper Climax,4.0,1961,BRA,11
260,261,John Surtees,GBR,Cooper Climax,4.0,1961,SUR,11
261,262,Olivier Gendebien,BEL,Lotus Climax,3.0,1961,GEN,13
262,263,Jackie Lewis,GBR,Cooper Climax,3.0,1961,LEW,13
263,264,Jo Bonnier,SWE,Porsche,3.0,1961,BON,13
264,265,Graham Hill,GBR,BRM Climax,3.0,1961,HIL,13
265,266,Roy Salvadori,GBR,Cooper Climax,2.0,1961,SAL,17
266,267,Graham Hill,GBR,BRM,42.0,1962,HIL,1
267,268,Jim Clark,GBR,Lotus Climax,30.0,1962,CLA,2
268,269,Bruce McLaren,NZL,Cooper Climax,27.0,1962,MCL,3
269,270,John Surtees,GBR,Lola Climax,19.0,1962,SUR,4
270,271,Dan Gurney,USA,Porsche,15.0,1962,GUR,5
271,272,Phil Hill,USA,Ferrari,14.0,1962,HIL,6
272,273,Tony Maggs,RSA,Cooper Climax,13.0,1962,MAG,7
273,274,Richie Ginther,USA,BRM,10.0,1962,GIN,8
274,275,Jack Brabham,AUS,Brabham Climax,9.0,1962,BRA,9
275,276,Trevor Taylor,GBR,Lotus Climax,6.0,1962,TAY,10
276,277,Giancarlo Baghetti,ITA,Ferrari,5.0,1962,BAG,11
277,278,Lorenzo Bandini,ITA,Ferrari,4.0,1962,BAN,12
278,279,Ricardo Rodriguez,MEX,Ferrari,4.0,1962,ROD,12
279,280,Willy Mairesse,BEL,Ferrari,3.0,1962,MAI,14
280,281,Jo Bonnier,SWE,Porsche,3.0,1962,BON,14
281,282,Innes Ireland,GBR,Lotus Climax,2.0,1962,IRE,16
282,283,Carel Godin de Beaufort,NED,Porsche,2.0,1962,DEB,16
283,284,Masten Gregory,USA,Lotus BRM,1.0,1962,GRE,18
284,285,Neville Lederle,RSA,Lotus Climax,1.0,1962,LED,18
285,286,Jim Clark,GBR,Lotus Climax,54.0,1963,CLA,1
286,287,Graham Hill,GBR,BRM,29.0,1963,HIL,2
287,288,Richie Ginther,USA,BRM,29.0,1963,GIN,2
288,289,John Surtees,GBR,Ferrari,22.0,1963,SUR,4
289,290,Dan Gurney,USA,Brabham Climax,19.0,1963,GUR,5
290,291,Bruce McLaren,NZL,Cooper Climax,17.0,1963,MCL,6
291,292,Jack Brabham,AUS,Brabham Climax,14.0,1963,BRA,7
292,293,Tony Maggs,RSA,Cooper Climax,9.0,1963,MAG,8
293,294,Innes Ireland,GBR,BRP BRM,6.0,1963,IRE,9
294,295,Lorenzo Bandini,ITA,Ferrari,6.0,1963,BAN,9
295,296,Jo Bonnier,SWE,Cooper Climax,6.0,1963,BON,9
296,297,Gerhard Mitter,GER,Porsche,3.0,1963,MIT,12
297,298,Jim Hall,USA,Lotus BRM,3.0,1963,HAL,12
298,299,Carel Godin de Beaufort,NED,Porsche,2.0,1963,DEB,14
299,300,Trevor Taylor,GBR,Lotus Climax,1.0,1963,TAY,15
300,301,Ludovico Scarfiotti,ITA,Ferrari,1.0,1963,SCA,15
301,302,Jo Siffert,SUI,Lotus BRM,1.0,1963,SIF,15
302,303,Willy Mairesse,BEL,Ferrari,0.0,1963,MAI,18
303,304,Maurice Trintignant,FRA,BRM,0.0,1963,TRI,18
304,305,Tony Settember,USA,Scirocco BRM,0.0,1963,SET,18
305,306,Lucien Bianchi,BEL,Lola Climax,0.0,1963,BIA,18
306,307,Phil Hill,USA,ATS,0.0,1963,HIL,18
307,308,Giancarlo Baghetti,ITA,ATS,0.0,1963,BAG,18
308,309,Chris Amon,NZL,Lotus BRM,0.0,1963,AMO,18
309,310,Masten Gregory,USA,NaN,0.0,1963,GRE,18
310,311,Bob Anderson,GBR,Lola Climax,0.0,1963,AND,18
311,312,Ian Raby,GBR,Gilby BRM,0.0,1963,RAB,18
312,313,John Campbell-Jones,GBR,Lola Climax,0.0,1963,CAM,18
313,314,Ian Burgess,GBR,Scirocco BRM,0.0,1963,BUR,18
314,315,Mike Hailwood,GBR,NaN,0.0,1963,HAI,18
315,316,Mario de Araujo Cabral,POR,Cooper Climax,0.0,1963,DEA,18
316,317,Bernard Collomb,FRA,Lotus Climax,0.0,1963,COL,18
317,318,Mike Spence,GBR,Lotus Climax,0.0,1963,SPE,18
318,319,Peter Broeker,CAN,Stebro Ford,0.0,1963,BRO,18
319,320,Rodger Ward,USA,Lotus BRM,0.0,1963,WAR,18
320,321,Pedro Rodriguez,MEX,Lotus Climax,0.0,1963,ROD,18
321,322,Hap Sharp,USA,Lotus BRM,0.0,1963,SHA,18
322,323,Moises Solana,MEX,BRM,0.0,1963,SOL,18
323,324,Doug Serrurier,RSA,LDS Alfa Romeo,0.0,1963,SER,18
324,325,Trevor Blokdyk,RSA,Cooper Maserati,0.0,1963,BLO,18
325,326,Brausch Niemann,RSA,Lotus Ford,0.0,1963,NIE,18
326,327,John Love,RHO,Cooper Climax,0.0,1963,LOV,18
327,328,Ernie Pieterse,RSA,Lotus Climax,0.0,1963,PIE,18
328,329,Peter de Klerk,RSA,Alfa Romeo,0.0,1963,DEK,18
329,330,Sam Tingle,RHO,LDS Alfa Romeo,0.0,1963,TIN,18
330,331,David Prophet,GBR,Brabham Ford,0.0,1963,PRO,18
331,332,John Surtees,GBR,Ferrari,40.0,1964,SUR,1
332,333,Graham Hill,GBR,BRM,39.0,1964,HIL,2
333,334,Jim Clark,GBR,Lotus Climax,32.0,1964,CLA,3
334,335,Lorenzo Bandini,ITA,Ferrari,23.0,1964,BAN,4
335,336,Richie Ginther,USA,BRM,23.0,1964,GIN,4
336,337,Dan Gurney,USA,Brabham Climax,19.0,1964,GUR,6
337,338,Bruce McLaren,NZL,Cooper Climax,13.0,1964,MCL,7
338,339,Peter Arundell,GBR,Lotus Climax,11.0,1964,ARU,8
339,340,Jack Brabham,AUS,Brabham Climax,11.0,1964,BRA,8
340,341,Jo Siffert,SUI,Brabham BRM,7.0,1964,SIF,10
341,342,Bob Anderson,GBR,Brabham Climax,5.0,1964,AND,11
342,343,Tony Maggs,RSA,BRM,4.0,1964,MAG,12
343,344,Mike Spence,GBR,Lotus Climax,4.0,1964,SPE,12
344,345,Innes Ireland,GBR,BRP BRM,4.0,1964,IRE,12
345,346,Jo Bonnier,SWE,Brabham Climax,3.0,1964,BON,15
346,347,Chris Amon,NZL,Lotus BRM,2.0,1964,AMO,16
347,348,Maurice Trintignant,FRA,BRM,2.0,1964,TRI,16
348,349,Walt Hansgen,USA,Lotus Climax,2.0,1964,HAN,16
349,350,Mike Hailwood,GBR,Lotus BRM,1.0,1964,HAI,19
350,351,Phil Hill,USA,Cooper Climax,1.0,1964,HIL,19
351,352,Trevor Taylor,GBR,BRP BRM,1.0,1964,TAY,19
352,353,Pedro Rodriguez,MEX,Ferrari,1.0,1964,ROD,19
353,354,Jim Clark,GBR,Lotus Climax,54.0,1965,CLA,1
354,355,Graham Hill,GBR,BRM,40.0,1965,HIL,2
355,356,Jackie Stewart,GBR,BRM,33.0,1965,STE,3
356,357,Dan Gurney,USA,Brabham Climax,25.0,1965,GUR,4
357,358,John Surtees,GBR,Ferrari,17.0,1965,SUR,5
358,359,Lorenzo Bandini,ITA,Ferrari,13.0,1965,BAN,6
359,360,Richie Ginther,USA,Honda,11.0,1965,GIN,7
360,361,Mike Spence,GBR,Lotus Climax,10.0,1965,SPE,8
361,362,Bruce McLaren,NZL,Cooper Climax,10.0,1965,MCL,8
362,363,Jack Brabham,AUS,Brabham Climax,9.0,1965,BRA,10
363,364,Denny Hulme,NZL,Brabham Climax,5.0,1965,HUL,11
364,365,Jo Siffert,SUI,Brabham BRM,5.0,1965,SIF,11
365,366,Jochen Rindt,AUT,Cooper Climax,4.0,1965,RIN,13
366,367,Pedro Rodriguez,MEX,Ferrari,2.0,1965,ROD,14
367,368,Ronnie Bucknum,USA,Honda,2.0,1965,BUC,14
368,369,Richard Attwood,GBR,Lotus BRM,2.0,1965,ATT,14
369,370,Jack Brabham,AUS,Brabham Repco,42.0,1966,BRA,1