In [ ]:
import numpy as np
import pandas as pd
import warnings

warnings.filterwarnings('ignore')
pd.set_option('display.max_rows', None)    # Muestra todas las filas (para muchas columnas)
pd.set_option('display.max_columns', None) # Muestra todas las columnas
pd.set_option('display.width', None)       # Ajusta el ancho
pd.set_option('display.max_colwidth', None)# Muestra todo el contenido de cada celda

In [ ]:
drivers_c = pd.read_csv('csv_limpios/drivers_c.csv')
drivers_updated_c = pd.read_csv('csv_limpios/drivers_updated_c.csv')

In [ ]:
drivers_c

In [ ]:
drivers_updated_c

### Elimino columna CODE en drivers_c y drivers_updated_c porque no la voy a utilizar

In [ ]:
drivers_updated_c.drop(columns=['Code'], inplace=True)
drivers_c.drop(columns=['code'], inplace=True)

### Uno las columnas 'forename' y 'surname' de drivers_c en la columna creada 'Driver'

In [ ]:
# Creo columna 'Driver' en drivers_c juntando 'forename' y 'surname'
drivers_c['Driver'] = drivers_c['forename'] + ' ' + drivers_c['surname']

In [ ]:
# Posiciono la columna 'Driver' al inicio del DataFrame
drivers_c = drivers_c[['Driver'] + [col for col in drivers_c.columns if col != 'Driver']]

In [ ]:
# Elimino las columnas 'forename', 'surname' y 'driverRef' de drivers_c
drivers_c.drop(columns=['forename', 'surname', 'driverRef'], inplace=True)

### Relleno los null con los datos correctos de cada piloto en la columna Car

In [ ]:
# Muestro solo las filas donde hay un null en la columna 'Car' dentro de drivers_updated_c
drivers_updated_c[drivers_updated_c['Car'].isnull()]

In [ ]:
# Creo lista para rellenar datos de la columna 'Car' de drivers_updated_c donde hay un null

mapping_id = {
    (17, 1950): 'Ferrari',
    (18, 1950): 'Talbot-Lago',
    (22, 1950): 'Talbot-Lago',
    (36, 1951): 'Talbot-Lago',
    (54, 1952): 'Cooper Bristol',
    (310, 1963): 'Reg Parnell Racing',
    (315, 1963): 'Reg Parnell Racing',
    (447, 1969): 'Lotus Ford',
    (479, 1971): 'STP March Racing Team',
    (493, 1971): 'McLaren Ford',
    (494, 1971): 'Frank Williams Racing Cars/Williams',
}

def asignar_car_id(row):
    key = (row['Driver_ID'], row['year'])
    return mapping_id.get(key, row['Car'])

drivers_updated_c['Car'] = drivers_updated_c.apply(asignar_car_id, axis=1)

--------------------------------------------------

### Pilotos Unicos 'drivers_updated_c'

In [ ]:
pilotos_unicos = drivers_updated_c['Driver'].unique().tolist()
pilotos_unicos.sort()  # ordena alfabéticamente

for piloto in pilotos_unicos:
    print(piloto)

In [ ]:
# Sumar los valores totales dentro de la variable pilotos_unicos
total_pilotos = len(pilotos_unicos)
print(f'Total de pilotos únicos: {total_pilotos}')

### Pilotos Unicos 'drivers_c'

In [ ]:
pilotos_unicos2 = drivers_c['Driver'].unique().tolist()
pilotos_unicos2.sort()  # ordena alfabéticamente

for piloto in pilotos_unicos2:
    print(piloto)

In [87]:
# Sumar los valores totales dentro de la variable pilotos_unicos
total_pilotos2 = len(pilotos_unicos2)
print(f'Total de pilotos únicos: {total_pilotos2}')

Total de pilotos únicos: 861

------------------------------------------------

### Escuderias totales

In [ ]:
# Muestro los valores unicos de la columna 'Car' dentro de drivers_updated_c
drivers_updated_c['Car'].drop_duplicates()

### Guardo cambios de los DataFrames

In [94]:
# Creo codigo para guardar los DataFrames actualizados
drivers_c.to_csv('csv_limpios/drivers_data.csv', index=False)
drivers_updated_c.to_csv('csv_limpios/drivers_GP.csv', index=False)

In [95]:
# Creo codigo para cargar los DataFrames actualizados
drivers_data = pd.read_csv('csv_limpios/drivers_data.csv')
drivers_GP = pd.read_csv('csv_limpios/drivers_GP.csv')

In [96]:
drivers_c

,Driver,born,nationality,url
0,Lewis Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,Nick Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,Nico Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,Fernando Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,Heikki Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
5,Kazuki Nakajima,1985-01-11,Japanese,http://en.wikipedia.org/wiki/Kazuki_Nakajima
6,Sébastien Bourdais,1979-02-28,French,http://en.wikipedia.org/wiki/S%C3%A9bastien_Bourdais
7,Kimi Räikkönen,1979-10-17,Finnish,http://en.wikipedia.org/wiki/Kimi_R%C3%A4ikk%C3%B6nen
8,Robert Kubica,1984-12-07,Polish,http://en.wikipedia.org/wiki/Robert_Kubica
9,Timo Glock,1982-03-18,German,http://en.wikipedia.org/wiki/Timo_Glock
10,Takuma Sato,1977-01-28,Japanese,http://en.wikipedia.org/wiki/Takuma_Sato
11,Nelson Piquet Jr.,1985-07-25,Brazilian,"http://en.wikipedia.org/wiki/Nelson_Piquet,_Jr."
12,Felipe Massa,1981-04-25,Brazilian,http://en.wikipedia.org/wiki/Felipe_Massa
13,David Coulthard,1971-03-27,British,http://en.wikipedia.org/wiki/David_Coulthard
14,Jarno Trulli,1974-07-13,Italian,http://en.wikipedia.org/wiki/Jarno_Trulli
15,Adrian Sutil,1983-01-11,German,http://en.wikipedia.org/wiki/Adrian_Sutil
16,Mark Webber,1976-08-27,Australian,http://en.wikipedia.org/wiki/Mark_Webber_(racing_driver)
17,Jenson Button,1980-01-19,British,http://en.wikipedia.org/wiki/Jenson_Button
18,Anthony Davidson,1979-04-18,British,http://en.wikipedia.org/wiki/Anthony_Davidson
19,Sebastian Vettel,1987-07-03,German,http://en.wikipedia.org/wiki/Sebastian_Vettel
20,Giancarlo Fisichella,1973-01-14,Italian,http://en.wikipedia.org/wiki/Giancarlo_Fisichella
21,Rubens Barrichello,1972-05-23,Brazilian,http://en.wikipedia.org/wiki/Rubens_Barrichello
22,Ralf Schumacher,1975-06-30,German,http://en.wikipedia.org/wiki/Ralf_Schumacher
23,Vitantonio Liuzzi,1980-08-06,Italian,http://en.wikipedia.org/wiki/Vitantonio_Liuzzi
24,Alexander Wurz,1974-02-15,Austrian,http://en.wikipedia.org/wiki/Alexander_Wurz
25,Scott Speed,1983-01-24,American,http://en.wikipedia.org/wiki/Scott_Speed
26,Christijan Albers,1979-04-16,Dutch,http://en.wikipedia.org/wiki/Christijan_Albers
27,Markus Winkelhock,1980-06-13,German,http://en.wikipedia.org/wiki/Markus_Winkelhock
28,Sakon Yamamoto,1982-07-09,Japanese,http://en.wikipedia.org/wiki/Sakon_Yamamoto
29,Michael Schumacher,1969-01-03,German,http://en.wikipedia.org/wiki/Michael_Schumacher
30,Juan Pablo Montoya,1975-09-20,Colombian,http://en.wikipedia.org/wiki/Juan_Pablo_Montoya
31,Christian Klien,1983-02-07,Austrian,http://en.wikipedia.org/wiki/Christian_Klien
32,Tiago Monteiro,1976-07-24,Portuguese,http://en.wikipedia.org/wiki/Tiago_Monteiro
33,Yuji Ide,1975-01-21,Japanese,http://en.wikipedia.org/wiki/Yuji_Ide
34,Jacques Villeneuve,1971-04-09,Canadian,http://en.wikipedia.org/wiki/Jacques_Villeneuve
35,Franck Montagny,1978-01-05,French,http://en.wikipedia.org/wiki/Franck_Montagny
36,Pedro de la Rosa,1971-02-24,Spanish,http://en.wikipedia.org/wiki/Pedro_de_la_Rosa
37,Robert Doornbos,1981-09-23,Dutch,http://en.wikipedia.org/wiki/Robert_Doornbos
38,Narain Karthikeyan,1977-01-14,Indian,http://en.wikipedia.org/wiki/Narain_Karthikeyan
39,Patrick Friesacher,1980-09-26,Austrian,http://en.wikipedia.org/wiki/Patrick_Friesacher
40,Ricardo Zonta,1976-03-23,Brazilian,http://en.wikipedia.org/wiki/Ricardo_Zonta
41,Antônio Pizzonia,1980-09-11,Brazilian,http://en.wikipedia.org/wiki/Ant%C3%B4nio_Pizzonia
42,Cristiano da Matta,1973-09-19,Brazilian,http://en.wikipedia.org/wiki/Cristiano_da_Matta
43,Olivier Panis,1966-09-02,French,http://en.wikipedia.org/wiki/Olivier_Panis
44,Giorgio Pantano,1979-02-04,Italian,http://en.wikipedia.org/wiki/Giorgio_Pantano
45,Gianmaria Bruni,1981-05-30,Italian,http://en.wikipedia.org/wiki/Gianmaria_Bruni
46,Zsolt Baumgartner,1981-01-01,Hungarian,http://en.wikipedia.org/wiki/Zsolt_Baumgartner
47,Marc Gené,1974-03-29,Spanish,http://en.wikipedia.org/wiki/Marc_Gen%C3%A9
48,Heinz-Harald Frentzen,1967-05-18,German,http://en.wikipedia.org/wiki/Heinz-Harald_Frentzen
49,Jos Verstappen,1972-03-04,Dutch,http://en.wikipedia.org/wiki/Jos_Verstappen
50,Justin Wilson,1978-07-31,British,http://en.wikipedia.org/wiki/Justin_Wilson_(racing_driver)
51,Ralph Firman,1975-05-20,Irish,http://en.wikipedia.org/wiki/Ralph_Firman
52,Nicolas Kiesa,1978-03-03,Danish,http://en.wikipedia.org/wiki/Nicolas_Kiesa
53,Luciano Burti,1975-03-05,Brazilian,http://en.wikipedia.org/wiki/Luciano_Burti
54,Jean Alesi,1964-06-11,French,http://en.wikipedia.org/wiki/Jean_Alesi
55,Eddie Irvine,1965-11-10,British,http://en.wikipedia.org/wiki/Eddie_Irvine
56,Mika Häkkinen,1968-09-28,Finnish,http://en.wikipedia.org/wiki/Mika_H%C3%A4kkinen
57,Tarso Marques,1976-01-19,Brazilian,http://en.wikipedia.org/wiki/Tarso_Marques
58,Enrique Bernoldi,1978-10-19,Brazilian,http://en.wikipedia.org/wiki/Enrique_Bernoldi
59,Gastón Mazzacane,1975-05-08,Argentine,http://en.wikipedia.org/wiki/Gast%C3%B3n_Mazzacane
60,Tomáš Enge,1976-09-11,Czech,http://en.wikipedia.org/wiki/Tom%C3%A1%C5%A1_Enge
61,Alex Yoong,1976-07-20,Malaysian,http://en.wikipedia.org/wiki/Alex_Yoong
62,Mika Salo,1966-11-30,Finnish,http://en.wikipedia.org/wiki/Mika_Salo
63,Pedro Diniz,1970-05-22,Brazilian,http://en.wikipedia.org/wiki/Pedro_Diniz
64,Johnny Herbert,1964-06-25,British,http://en.wikipedia.org/wiki/Johnny_Herbert
65,Allan McNish,1969-12-29,British,http://en.wikipedia.org/wiki/Allan_McNish
66,Sébastien Buemi,1988-10-31,Swiss,http://en.wikipedia.org/wiki/S%C3%A9bastien_Buemi
67,Toranosuke Takagi,1974-02-12,Japanese,http://en.wikipedia.org/wiki/Toranosuke_Takagi
68,Luca Badoer,1971-01-25,Italian,http://en.wikipedia.org/wiki/Luca_Badoer
69,Alessandro Zanardi,1966-10-23,Italian,http://en.wikipedia.org/wiki/Alex_Zanardi
70,Damon Hill,1960-09-17,British,http://en.wikipedia.org/wiki/Damon_Hill
71,Stéphane Sarrazin,1975-11-02,French,http://en.wikipedia.org/wiki/St%C3%A9phane_Sarrazin
72,Ricardo Rosset,1968-07-27,Brazilian,http://en.wikipedia.org/wiki/Ricardo_Rosset
73,Esteban Tuero,1978-04-22,Argentine,http://en.wikipedia.org/wiki/Esteban_Tuero
74,Shinji Nakano,1971-04-01,Japanese,http://en.wikipedia.org/wiki/Shinji_Nakano
75,Jan Magnussen,1973-07-04,Danish,http://en.wikipedia.org/wiki/Jan_Magnussen
76,Gerhard Berger,1959-08-27,Austrian,http://en.wikipedia.org/wiki/Gerhard_Berger
77,Nicola Larini,1964-03-19,Italian,http://en.wikipedia.org/wiki/Nicola_Larini
78,Ukyo Katayama,1963-05-29,Japanese,http://en.wikipedia.org/wiki/Ukyo_Katayama
79,Vincenzo Sospiri,1966-10-07,Italian,http://en.wikipedia.org/wiki/Vincenzo_Sospiri
80,Gianni Morbidelli,1968-01-13,Italian,http://en.wikipedia.org/wiki/Gianni_Morbidelli
81,Norberto Fontana,1975-01-20,Argentine,http://en.wikipedia.org/wiki/Norberto_Fontana
82,Pedro Lamy,1972-03-20,Portuguese,http://en.wikipedia.org/wiki/Pedro_Lamy
83,Martin Brundle,1959-06-01,British,http://en.wikipedia.org/wiki/Martin_Brundle
84,Andrea Montermini,1964-05-30,Italian,http://en.wikipedia.org/wiki/Andrea_Montermini
85,Giovanni Lavaggi,1958-02-18,Italian,http://en.wikipedia.org/wiki/Giovanni_Lavaggi
86,Mark Blundell,1966-04-08,British,http://en.wikipedia.org/wiki/Mark_Blundell
87,Aguri Suzuki,1960-09-08,Japanese,http://en.wikipedia.org/wiki/Aguri_Suzuki
88,Taki Inoue,1963-09-05,Japanese,http://en.wikipedia.org/wiki/Taki_Inoue
89,Roberto Moreno,1959-02-11,Brazilian,http://en.wikipedia.org/wiki/Roberto_Moreno
90,Karl Wendlinger,1968-12-20,Austrian,http://en.wikipedia.org/wiki/Karl_Wendlinger
91,Bertrand Gachot,1962-12-23,Belgian,http://en.wikipedia.org/wiki/Bertrand_Gachot
92,Domenico Schiattarella,1967-11-17,Italian,http://en.wikipedia.org/wiki/Domenico_Schiattarella
93,Pierluigi Martini,1961-04-23,Italian,http://en.wikipedia.org/wiki/Pierluigi_Martini
94,Nigel Mansell,1953-08-08,British,http://en.wikipedia.org/wiki/Nigel_Mansell
95,Jean-Christophe Boullion,1969-12-27,French,http://en.wikipedia.org/wiki/Jean-Christophe_Boullion
96,Massimiliano Papis,1969-10-03,Italian,http://en.wikipedia.org/wiki/Massimiliano_Papis
97,Jean-Denis Délétraz,1963-10-01,Swiss,http://en.wikipedia.org/wiki/Jean-Denis_Deletraz
98,Gabriele Tarquini,1962-03-02,Italian,http://en.wikipedia.org/wiki/Gabriele_Tarquini
99,Érik Comas,1963-09-28,French,http://en.wikipedia.org/wiki/%C3%89rik_Comas
100,David Brabham,1965-09-05,Australian,http://en.wikipedia.org/wiki/David_Brabham
101,Ayrton Senna,1960-03-21,Brazilian,http://en.wikipedia.org/wiki/Ayrton_Senna
102,Éric Bernard,1964-08-24,French,http://en.wikipedia.org/wiki/%C3%89ric_Bernard
103,Christian Fittipaldi,1971-01-18,Brazilian,http://en.wikipedia.org/wiki/Christian_Fittipaldi
104,Michele Alboreto,1956-12-23,Italian,http://en.wikipedia.org/wiki/Michele_Alboreto
105,Olivier Beretta,1969-11-23,Monegasque,http://en.wikipedia.org/wiki/Olivier_Beretta
106,Roland Ratzenberger,1960-07-04,Austrian,http://en.wikipedia.org/wiki/Roland_Ratzenberger
107,Paul Belmondo,1963-04-23,French,http://en.wikipedia.org/wiki/Paul_Belmondo
108,Jyrki Järvilehto,1966-01-31,Finnish,http://en.wikipedia.org/wiki/Jyrki_J%C3%A4rvilehto
109,Andrea de Cesaris,1959-05-31,Italian,http://en.wikipedia.org/wiki/Andrea_de_Cesaris
110,Jean-Marc Gounon,1963-01-01,French,http://en.wikipedia.org/wiki/Jean-Marc_Gounon
111,Philippe Alliot,1954-07-27,French,http://en.wikipedia.org/wiki/Philippe_Alliot
112,Philippe Adams,1969-11-19,Belgian,http://en.wikipedia.org/wiki/Philippe_Adams
113,Yannick Dalmas,1961-07-28,French,http://en.wikipedia.org/wiki/Yannick_Dalmas
114,Hideki Noda,1969-03-07,Japanese,http://en.wikipedia.org/wiki/Hideki_Noda
115,Franck Lagorce,1968-09-01,French,http://en.wikipedia.org/wiki/Franck_Lagorce
116,Alain Prost,1955-02-24,French,http://en.wikipedia.org/wiki/Alain_Prost
117,Derek Warwick,1954-08-27,British,http://en.wikipedia.org/wiki/Derek_Warwick
118,Riccardo Patrese,1954-04-17,Italian,http://en.wikipedia.org/wiki/Riccardo_Patrese
119,Fabrizio Barbazza,1963-04-02,Italian,http://en.wikipedia.org/wiki/Fabrizio_Barbazza
120,Michael Andretti,1962-10-05,American,http://en.wikipedia.org/wiki/Michael_Andretti
121,Ivan Capelli,1963-05-24,Italian,http://en.wikipedia.org/wiki/Ivan_Capelli
122,Thierry Boutsen,1957-07-13,Belgian,http://en.wikipedia.org/wiki/Thierry_Boutsen
123,Marco Apicella,1965-10-07,Italian,http://en.wikipedia.org/wiki/Marco_Apicella
124,Emanuele Naspetti,1968-02-24,Italian,http://en.wikipedia.org/wiki/Emanuele_Naspetti
125,Toshio Suzuki,1955-03-10,Japanese,http://en.wikipedia.org/wiki/Toshio_Suzuki_(driver)
126,Maurício Gugelmin,1963-04-20,Brazilian,http://en.wikipedia.org/wiki/Maur%C3%ADcio_Gugelmin
127,Eric van de Poele,1961-09-30,Belgian,http://en.wikipedia.org/wiki/Eric_van_de_Poele
128,Olivier Grouillard,1958-09-02,French,http://en.wikipedia.org/wiki/Olivier_Grouillard
129,Andrea Chiesa,1964-05-06,Swiss,http://en.wikipedia.org/wiki/Andrea_Chiesa
130,Stefano Modena,1963-05-12,Italian,http://en.wikipedia.org/wiki/Stefano_Modena
131,Giovanna Amati,1959-07-20,Italian,http://en.wikipedia.org/wiki/Giovanna_Amati
132,Alex Caffi,1964-03-18,Italian,http://en.wikipedia.org/wiki/Alex_Caffi
133,Enrico Bertaggia,1964-09-19,Italian,http://en.wikipedia.org/wiki/Enrico_Bertaggia
134,Perry McCarthy,1961-03-03,British,http://en.wikipedia.org/wiki/Perry_McCarthy
135,Jan Lammers,1956-06-02,Dutch,http://en.wikipedia.org/wiki/Jan_Lammers
136,Nelson Piquet,1952-08-17,Brazilian,http://en.wikipedia.org/wiki/Nelson_Piquet
137,Satoru Nakajima,1953-02-23,Japanese,http://en.wikipedia.org/wiki/Satoru_Nakajima
138,Emanuele Pirro,1962-01-12,Italian,http://en.wikipedia.org/wiki/Emanuele_Pirro
139,Stefan Johansson,1956-09-08,Swedish,http://en.wikipedia.org/wiki/Stefan_Johansson
140,Julian Bailey,1961-10-09,British,http://en.wikipedia.org/wiki/Julian_Bailey
141,Pedro Chaves,1965-02-27,Portuguese,http://en.wikipedia.org/wiki/Pedro_Chaves
142,Michael Bartels,1968-03-08,German,http://en.wikipedia.org/wiki/Michael_Bartels
143,Naoki Hattori,1966-06-13,Japanese,http://en.wikipedia.org/wiki/Naoki_Hattori
144,Alessandro Nannini,1959-07-07,Italian,http://en.wikipedia.org/wiki/Alessandro_Nannini
145,Bernd Schneider,1964-07-20,German,http://en.wikipedia.org/wiki/Bernd_Schneider_(racecar_driver)
146,Paolo Barilla,1961-04-20,Italian,http://en.wikipedia.org/wiki/Paolo_Barilla
147,Gregor Foitek,1965-03-27,Swiss,http://en.wikipedia.org/wiki/Gregor_Foitek
148,Claudio Langes,1960-07-20,Italian,http://en.wikipedia.org/wiki/Claudio_Langes
149,Gary Brabham,1961-03-29,Australian,http://en.wikipedia.org/wiki/Gary_Brabham
150,Martin Donnelly,1964-03-26,British,http://en.wikipedia.org/wiki/Martin_Donnelly_(racing_driver)
151,Bruno Giacomelli,1952-09-10,Italian,http://en.wikipedia.org/wiki/Bruno_Giacomelli
152,Jaime Alguersuari,1990-03-23,Spanish,http://en.wikipedia.org/wiki/Jaime_Alguersuari
153,Romain Grosjean,1986-04-17,French,http://en.wikipedia.org/wiki/Romain_Grosjean
154,Kamui Kobayashi,1986-09-13,Japanese,http://en.wikipedia.org/wiki/Kamui_Kobayashi
155,Jonathan Palmer,1956-11-07,British,http://en.wikipedia.org/wiki/Jonathan_Palmer
156,Christian Danner,1958-04-04,German,http://en.wikipedia.org/wiki/Christian_Danner
157,Eddie Cheever,1958-01-10,American,http://en.wikipedia.org/wiki/Eddie_Cheever
158,Luis Pérez-Sala,1959-05-15,Spanish,http://en.wikipedia.org/wiki/Luis_Perez-Sala
159,Piercarlo Ghinzani,1952-01-16,Italian,http://en.wikipedia.org/wiki/Piercarlo_Ghinzani
160,Volker Weidler,1962-03-18,German,http://en.wikipedia.org/wiki/Volker_Weidler
161,Pierre-Henri Raphanel,1961-05-27,French,http://en.wikipedia.org/wiki/Pierre-Henri_Raphanel
162,René Arnoux,1948-07-04,French,http://en.wikipedia.org/wiki/Ren%C3%A9_Arnoux
163,Joachim Winkelhock,1960-10-24,German,http://en.wikipedia.org/wiki/Joachim_Winkelhock
164,Oscar Larrauri,1954-08-19,Argentine,http://en.wikipedia.org/wiki/Oscar_Larrauri
165,Philippe Streiff,1955-06-26,French,http://en.wikipedia.org/wiki/Philippe_Streiff
166,Adrián Campos,1960-06-17,Spanish,http://en.wikipedia.org/wiki/Adri%C3%A1n_Campos
167,Jean-Louis Schlesser,1948-09-12,French,http://en.wikipedia.org/wiki/Jean-Louis_Schlesser
168,Pascal Fabre,1960-01-09,French,http://en.wikipedia.org/wiki/Pascal_Fabre
169,Teo Fabi,1955-03-09,Italian,http://en.wikipedia.org/wiki/Teo_Fabi
170,Franco Forini,1958-09-22,Swiss,http://en.wikipedia.org/wiki/Franco_Forini
171,Jacques Laffite,1943-11-21,French,http://en.wikipedia.org/wiki/Jacques_Laffite
172,Elio de Angelis,1958-03-26,Italian,http://en.wikipedia.org/wiki/Elio_de_Angelis
173,Johnny Dumfries,1958-04-26,British,http://en.wikipedia.org/wiki/Johnny_Dumfries
174,Patrick Tambay,1949-06-25,French,http://en.wikipedia.org/wiki/Patrick_Tambay
175,Marc Surer,1951-09-18,Swiss,http://en.wikipedia.org/wiki/Marc_Surer
176,Keke Rosberg,1948-12-06,Finnish,http://en.wikipedia.org/wiki/Keke_Rosberg
177,Alan Jones,1946-11-02,Australian,http://en.wikipedia.org/wiki/Alan_Jones_(Formula_1)
178,Huub Rothengatter,1954-10-08,Dutch,http://en.wikipedia.org/wiki/Huub_Rothengatter
179,Allen Berg,1961-08-01,Canadian,http://en.wikipedia.org/wiki/Allen_Berg
180,Manfred Winkelhock,1951-10-06,German,http://en.wikipedia.org/wiki/Manfred_Winkelhock
181,Niki Lauda,1949-02-22,Austrian,http://en.wikipedia.org/wiki/Niki_Lauda
182,François Hesnault,1956-12-30,French,http://en.wikipedia.org/wiki/Fran%C3%A7ois_Hesnault
183,Mauro Baldi,1954-01-31,Italian,http://en.wikipedia.org/wiki/Mauro_Baldi
184,Stefan Bellof,1957-11-20,German,http://en.wikipedia.org/wiki/Stefan_Bellof
185,Kenny Acheson,1957-11-27,British,http://en.wikipedia.org/wiki/Kenny_Acheson
186,John Watson,1946-05-04,British,http://en.wikipedia.org/wiki/John_Watson_(racing_driver)
187,Johnny Cecotto,1956-01-25,Venezuelan,http://en.wikipedia.org/wiki/Johnny_Cecotto
188,Jo Gartner,1954-01-24,Austrian,http://en.wikipedia.org/wiki/Jo_Gartner
189,Corrado Fabi,1961-04-12,Italian,http://en.wikipedia.org/wiki/Corrado_Fabi
190,Mike Thackwell,1961-03-30,New Zealander,http://en.wikipedia.org/wiki/Mike_Thackwell
191,Chico Serra,1957-02-03,Brazilian,http://en.wikipedia.org/wiki/Chico_Serra
192,Danny Sullivan,1950-03-09,American,http://en.wikipedia.org/wiki/Danny_Sullivan
193,Eliseo Salazar,1954-11-14,Chilean,http://en.wikipedia.org/wiki/Eliseo_Salazar
194,Roberto Guerrero,1958-11-16,Colombian,http://en.wikipedia.org/wiki/Roberto_Guerrero
195,Raul Boesel,1957-12-04,Brazilian,http://en.wikipedia.org/wiki/Raul_Boesel
196,Jean-Pierre Jarier,1946-07-10,French,http://en.wikipedia.org/wiki/Jean-Pierre_Jarier
197,Jacques Villeneuve Sr.,1953-11-04,Canadian,http://en.wikipedia.org/wiki/Jacques_Villeneuve_(elder)
198,Carlos Reutemann,1942-04-12,Argentine,http://en.wikipedia.org/wiki/Carlos_Reutemann
199,Jochen Mass,1946-09-30,German,http://en.wikipedia.org/wiki/Jochen_Mass
200,Slim Borgudd,1946-11-25,Swedish,http://en.wikipedia.org/wiki/Slim_Borgudd
201,Didier Pironi,1952-03-26,French,http://en.wikipedia.org/wiki/Didier_Pironi
202,Gilles Villeneuve,1950-01-18,Canadian,http://en.wikipedia.org/wiki/Gilles_Villeneuve
203,Riccardo Paletti,1958-06-15,Italian,http://en.wikipedia.org/wiki/Riccardo_Paletti
204,Brian Henton,1946-09-19,British,http://en.wikipedia.org/wiki/Brian_Henton
205,Derek Daly,1953-03-11,Irish,http://en.wikipedia.org/wiki/Derek_Daly
206,Mario Andretti,1940-02-28,American,http://en.wikipedia.org/wiki/Mario_Andretti
207,Emilio de Villota,1946-07-26,Spanish,http://en.wikipedia.org/wiki/Emilio_de_Villota
208,Geoff Lees,1951-05-01,British,http://en.wikipedia.org/wiki/Geoff_Lees
209,Tommy Byrne,1958-05-06,Irish,http://en.wikipedia.org/wiki/Tommy_Byrne_%28racing_driver%29
210,Rupert Keegan,1955-02-26,British,http://en.wikipedia.org/wiki/Rupert_Keegan
211,Hector Rebaque,1956-02-05,Mexican,http://en.wikipedia.org/wiki/Hector_Rebaque
212,Beppe Gabbiani,1957-01-02,Italian,http://en.wikipedia.org/wiki/Beppe_Gabbiani
213,Kevin Cogan,1956-03-31,American,http://en.wikipedia.org/wiki/Kevin_Cogan
214,Miguel Ángel Guerra,1953-08-31,Argentine,http://en.wikipedia.org/wiki/Miguel_Angel_Guerra
215,Siegfried Stohr,1952-10-10,Italian,http://en.wikipedia.org/wiki/Siegfried_Stohr
216,Ricardo Zunino,1949-04-13,Argentine,http://en.wikipedia.org/wiki/Ricardo_Zunino
217,Ricardo Londoño,1949-08-08,Colombian,http://en.wikipedia.org/wiki/Ricardo_Londo%C3%B1o
218,Jean-Pierre Jabouille,1942-10-01,French,http://en.wikipedia.org/wiki/Jean-Pierre_Jabouille
219,Giorgio Francia,1947-11-08,Italian,http://en.wikipedia.org/wiki/Giorgio_Francia
220,Patrick Depailler,1944-08-09,French,http://en.wikipedia.org/wiki/Patrick_Depailler
221,Jody Scheckter,1950-01-29,South African,http://en.wikipedia.org/wiki/Jody_Scheckter
222,Clay Regazzoni,1939-09-05,Swiss,http://en.wikipedia.org/wiki/Clay_Regazzoni
223,Emerson Fittipaldi,1946-12-12,Brazilian,http://en.wikipedia.org/wiki/Emerson_Fittipaldi
224,Dave Kennedy,1953-01-15,Irish,http://en.wikipedia.org/wiki/David_Kennedy_(racing_driver)
225,Stephen South,1952-02-19,British,http://en.wikipedia.org/wiki/Stephen_South
226,Tiff Needell,1951-10-29,British,http://en.wikipedia.org/wiki/Tiff_Needell
227,Desiré Wilson,1953-11-26,South African,http://en.wikipedia.org/wiki/Desir%C3%A9_Wilson
228,Harald Ertl,1948-08-31,Austrian,http://en.wikipedia.org/wiki/Harald_Ertl
229,Vittorio Brambilla,1937-11-11,Italian,http://en.wikipedia.org/wiki/Vittorio_Brambilla
230,James Hunt,1947-08-29,British,http://en.wikipedia.org/wiki/James_Hunt
231,Arturo Merzario,1943-03-11,Italian,http://en.wikipedia.org/wiki/Arturo_Merzario
232,Hans-Joachim Stuck,1951-01-01,German,http://en.wikipedia.org/wiki/Hans_Joachim_Stuck
233,Gianfranco Brancatelli,1950-01-18,Italian,http://en.wikipedia.org/wiki/Gianfranco_Brancatelli
234,Jacky Ickx,1945-01-01,Belgian,http://en.wikipedia.org/wiki/Jacky_Ickx
235,Patrick Gaillard,1952-02-12,French,http://en.wikipedia.org/wiki/Patrick_Gaillard
236,Alex Ribeiro,1948-11-07,Brazilian,http://en.wikipedia.org/wiki/Alex_Ribeiro
237,Ronnie Peterson,1944-02-14,Swedish,http://en.wikipedia.org/wiki/Ronnie_Peterson
238,Brett Lunger,1945-11-14,American,http://en.wikipedia.org/wiki/Brett_Lunger

In [92]:
drivers_GP

,Driver_ID,Driver,Nationality,Car,PTS,year,Final_Pos
0,1,Nino Farina,ITA,Alfa Romeo,30.0,1950,1
1,2,Juan Manuel Fangio,ARG,Alfa Romeo,27.0,1950,2
2,3,Luigi Fagioli,ITA,Alfa Romeo,24.0,1950,3
3,4,Louis Rosier,FRA,Talbot-Lago,13.0,1950,4
4,5,Alberto Ascari,ITA,Ferrari,11.0,1950,5
5,6,Johnnie Parsons,USA,Kurtis Kraft Offenhauser,9.0,1950,6
6,7,Bill Holland,USA,Deidt Offenhauser,6.0,1950,7
7,8,Prince Bira,THA,Maserati,5.0,1950,8
8,9,Reg Parnell,GBR,Maserati,4.0,1950,9
9,10,Louis Chiron,MON,Maserati,4.0,1950,9
10,11,Mauri Rose,USA,Deidt Offenhauser,4.0,1950,9
11,12,Peter Whitehead,GBR,Ferrari,4.0,1950,9
12,13,Yves Giraud Cabantous,FRA,Talbot-Lago,3.0,1950,13
13,14,Raymond Sommer,FRA,Talbot-Lago,3.0,1950,13
14,15,Cecil Green,USA,Kurtis Kraft Offenhauser,3.0,1950,13
15,16,Robert Manzon,FRA,Simca-Gordini,3.0,1950,13
16,17,Dorino Serafini,ITA,Ferrari,3.0,1950,13
17,18,Philippe Etancelin,FRA,Talbot-Lago,3.0,1950,13
18,19,Felice Bonetto,ITA,Maserati Milano,2.0,1950,19
19,20,Tony Bettenhausen,USA,Deidt Offenhauser,1.0,1950,20
20,21,Joie Chitwood,USA,Kurtis Kraft Offenhauser,1.0,1950,20
21,22,Eugene Chaboud,FRA,Talbot-Lago,1.0,1950,20
22,23,Juan Manuel Fangio,ARG,Alfa Romeo,31.0,1951,1
23,24,Alberto Ascari,ITA,Ferrari,25.0,1951,2
24,25,Jose Froilan Gonzalez,ARG,Ferrari,24.0,1951,3
25,26,Nino Farina,ITA,Alfa Romeo,19.0,1951,4
26,27,Luigi Villoresi,ITA,Ferrari,15.0,1951,5
27,28,Piero Taruffi,ITA,Ferrari,10.0,1951,6
28,29,Lee Wallard,USA,Kurtis Kraft Offenhauser,9.0,1951,7
29,30,Felice Bonetto,ITA,Alfa Romeo,7.0,1951,8
30,31,Mike Nazaruk,USA,Kurtis Kraft Offenhauser,6.0,1951,9
31,32,Reg Parnell,GBR,BRM,5.0,1951,10
32,33,Luigi Fagioli,ITA,Alfa Romeo,4.0,1951,11
33,34,Consalvo Sanesi,ITA,Alfa Romeo,3.0,1951,12
34,35,Andy Linden,USA,Sherman Offenhauser,3.0,1951,12
35,36,Louis Rosier,FRA,Talbot-Lago,3.0,1951,12
36,37,Toulo de Graffenried,SUI,Alfa Romeo,2.0,1951,15
37,38,Manny Ayulo,USA,Kurtis Kraft Offenhauser,2.0,1951,15
38,39,Bobby Ball,USA,Schroeder Offenhauser,2.0,1951,15
39,40,Jack McGrath,USA,Kurtis Kraft Offenhauser,2.0,1951,15
40,41,Yves Giraud Cabantous,FRA,Talbot-Lago,2.0,1951,15
41,42,Alberto Ascari,ITA,Ferrari,36.0,1952,1
42,43,Nino Farina,ITA,Ferrari,24.0,1952,2
43,44,Piero Taruffi,ITA,Ferrari,22.0,1952,3
44,45,Rudi Fischer,SUI,Ferrari,10.0,1952,4
45,46,Mike Hawthorn,GBR,Cooper Bristol,10.0,1952,4
46,47,Robert Manzon,FRA,Gordini,9.0,1952,6
47,48,Troy Ruttman,USA,Kuzma Offenhauser,8.0,1952,7
48,49,Luigi Villoresi,ITA,Ferrari,8.0,1952,7
49,50,Jose Froilan Gonzalez,ARG,Maserati,6.5,1952,9
50,51,Jim Rathmann,USA,Kurtis Kraft Offenhauser,6.0,1952,10
51,52,Jean Behra,FRA,Gordini,6.0,1952,10
52,53,Sam Hanks,USA,Kurtis Kraft Offenhauser,4.0,1952,12
53,54,Ken Wharton,GBR,Cooper Bristol,3.0,1952,13
54,55,Duane Carter,USA,Lesovsky Offenhauser,3.0,1952,13
55,56,Dennis Poore,GBR,Connaught Lea Francis,3.0,1952,13
56,57,Alan Brown,GBR,Cooper Bristol,2.0,1952,16
57,58,Art Cross,USA,Kurtis Kraft Offenhauser,2.0,1952,16
58,59,Paul Frere,BEL,Simca-Gordini,2.0,1952,16
59,60,Maurice Trintignant,FRA,Gordini,2.0,1952,16
60,61,Eric Thompson,GBR,Connaught Lea Francis,2.0,1952,16
61,62,Felice Bonetto,ITA,Maserati,2.0,1952,16
62,63,Bill Vukovich,USA,Kurtis Kraft Offenhauser,1.0,1952,22
63,64,Alberto Ascari,ITA,Ferrari,34.5,1953,1
64,65,Juan Manuel Fangio,ARG,Maserati,27.5,1953,2
65,66,Nino Farina,ITA,Ferrari,26.0,1953,3
66,67,Mike Hawthorn,GBR,Ferrari,19.0,1953,4
67,68,Luigi Villoresi,ITA,Ferrari,17.0,1953,5
68,69,Jose Froilan Gonzalez,ARG,Maserati,13.5,1953,6
69,70,Bill Vukovich,USA,Kurtis Kraft Offenhauser,9.0,1953,7
70,71,Toulo de Graffenried,SUI,Maserati,7.0,1953,8
71,72,Felice Bonetto,ITA,Maserati,6.5,1953,9
72,73,Art Cross,USA,Kurtis Kraft Offenhauser,6.0,1953,10
73,74,Onofre Marimon,ARG,Maserati,4.0,1953,11
74,75,Maurice Trintignant,FRA,Gordini,4.0,1953,11
75,76,Oscar Alfredo Galvez,ARG,Maserati,2.0,1953,13
76,77,Sam Hanks,USA,Kurtis Kraft Offenhauser,2.0,1953,13
77,78,Duane Carter,USA,Kurtis Kraft Offenhauser,2.0,1953,13
78,79,Jack McGrath,USA,Kurtis Kraft Offenhauser,2.0,1953,13
79,80,Hermann Lang,GER,Maserati,2.0,1953,13
80,81,Fred Agabashian,USA,Kurtis Kraft Offenhauser,1.5,1953,18
81,82,Paul Russo,USA,Kurtis Kraft Offenhauser,1.5,1953,18
82,83,Juan Manuel Fangio,ARG,Mercedes-Benz,42.0,1954,1
83,84,Jose Froilan Gonzalez,ARG,Ferrari,25.1,1954,2
84,85,Mike Hawthorn,GBR,Ferrari,24.6,1954,3
85,86,Maurice Trintignant,FRA,Ferrari,17.0,1954,4
86,87,Karl Kling,GER,Mercedes-Benz,12.0,1954,5
87,88,Bill Vukovich,USA,Kurtis Kraft Offenhauser,8.0,1954,6
88,89,Hans Herrmann,GER,Mercedes-Benz,8.0,1954,6
89,90,Nino Farina,ITA,Ferrari,6.0,1954,8
90,91,Jimmy Bryan,USA,Kuzma Offenhauser,6.0,1954,8
91,92,Luigi Musso,ITA,Maserati,6.0,1954,8
92,93,Roberto Mieres,ARG,Maserati,6.0,1954,8
93,94,Jack McGrath,USA,Kurtis Kraft Offenhauser,5.0,1954,12
94,95,Stirling Moss,GBR,Maserati,4.1,1954,13
95,96,Onofre Marimon,ARG,Maserati,4.1,1954,13
96,97,Robert Manzon,FRA,Ferrari,4.0,1954,15
97,98,Sergio Mantovani,ITA,Maserati,4.0,1954,15
98,99,Prince Bira,THA,Maserati,3.0,1954,17
99,100,Elie Bayol,FRA,Gordini,2.0,1954,18
100,101,Mike Nazaruk,USA,Kurtis Kraft Offenhauser,2.0,1954,18
101,102,Andre Pilette,BEL,Gordini,2.0,1954,18
102,103,Luigi Villoresi,ITA,Lancia,2.0,1954,18
103,104,Umberto Maglioli,ITA,Ferrari,2.0,1954,18
104,105,Troy Ruttman,USA,Kurtis Kraft Offenhauser,1.5,1954,23
105,106,Duane Carter,USA,Kurtis Kraft Offenhauser,1.5,1954,23
106,107,Alberto Ascari,ITA,Lancia,1.1,1954,25
107,108,Jean Behra,FRA,Gordini,0.1,1954,26
108,109,Juan Manuel Fangio,ARG,Mercedes-Benz,40.0,1955,1
109,110,Stirling Moss,GBR,Mercedes-Benz,23.0,1955,2
110,111,Eugenio Castellotti,ITA,Ferrari,12.0,1955,3
111,112,Maurice Trintignant,FRA,Ferrari,11.3,1955,4
112,113,Nino Farina,ITA,Ferrari,10.3,1955,5
113,114,Piero Taruffi,ITA,Mercedes-Benz,9.0,1955,6
114,115,Bob Sweikert,USA,Kurtis Kraft Offenhauser,8.0,1955,7
115,116,Roberto Mieres,ARG,Maserati,7.0,1955,8
116,117,Luigi Musso,ITA,Maserati,6.0,1955,9
117,118,Jean Behra,FRA,Maserati,6.0,1955,9
118,119,Karl Kling,GER,Mercedes-Benz,5.0,1955,11
119,120,Jimmy Davies,USA,Kurtis Kraft Offenhauser,4.0,1955,12
120,121,Paul Russo,USA,Kurtis Kraft Offenhauser,3.0,1955,13
121,122,Tony Bettenhausen,USA,Kurtis Kraft Offenhauser,3.0,1955,13
122,123,Johnny Thomson,USA,Kuzma Offenhauser,3.0,1955,13
123,124,Paul Frere,BEL,Ferrari,3.0,1955,13
124,125,Jose Froilan Gonzalez,ARG,Ferrari,2.0,1955,17
125,126,Cesare Perdisa,ITA,Maserati,2.0,1955,17
126,127,Luigi Villoresi,ITA,Lancia,2.0,1955,17
127,128,Carlos Menditeguy,ARG,Maserati,2.0,1955,17
128,129,Umberto Maglioli,ITA,Ferrari,1.3,1955,21
129,130,Hans Herrmann,GER,Mercedes-Benz,1.0,1955,22
130,131,Walt Faulkner,USA,Kurtis Kraft Offenhauser,1.0,1955,22
131,132,Bill Homeier,USA,Kurtis Kraft Offenhauser,1.0,1955,22
132,133,Bill Vukovich,USA,Kurtis Kraft Offenhauser,1.0,1955,22
133,134,Juan Manuel Fangio,ARG,Ferrari,30.0,1956,1
134,135,Stirling Moss,GBR,Maserati,27.0,1956,2
135,136,Peter Collins,GBR,Ferrari,25.0,1956,3
136,137,Jean Behra,FRA,Maserati,22.0,1956,4
137,138,Pat Flaherty,USA,Watson Offenhauser,8.0,1956,5
138,139,Eugenio Castellotti,ITA,Ferrari,7.5,1956,6
139,140,Sam Hanks,USA,Kurtis Kraft Offenhauser,6.0,1956,7
140,141,Paul Frere,BEL,Ferrari,6.0,1956,7
141,142,Paco Godia,ESP,Maserati,6.0,1956,7
142,143,Jack Fairman,GBR,Connaught Alta,5.0,1956,10
143,144,Mike Hawthorn,GBR,BRM,4.0,1956,11
144,145,Luigi Musso,ITA,Ferrari,4.0,1956,11
145,146,Don Freeland,USA,Phillips Offenhauser,4.0,1956,11
146,147,Ron Flockhart,GBR,Connaught Alta,4.0,1956,11
147,148,Johnnie Parsons,USA,Kuzma Offenhauser,3.0,1956,15
148,149,Harry Schell,USA,Vanwall,3.0,1956,15
149,150,Alfonso de Portago,ESP,Ferrari,3.0,1956,15
150,151,Cesare Perdisa,ITA,Maserati,3.0,1956,15
151,152,Olivier Gendebien,BEL,Ferrari,2.0,1956,19
152,153,Hermano da Silva Ramos,BRA,Gordini,2.0,1956,19
153,154,Dick Rathmann,USA,Kurtis Kraft Offenhauser,2.0,1956,19
154,155,Luigi Villoresi,ITA,Maserati,2.0,1956,19
155,156,Horace Gould,GBR,Maserati,2.0,1956,19
156,157,Louis Rosier,FRA,Maserati,2.0,1956,19
157,158,Gerino Gerini,ITA,Maserati,1.5,1956,25
158,159,Chico Landi,BRA,Maserati,1.5,1956,25
159,160,Paul Russo,USA,Kurtis Kraft Novi,1.0,1956,27
160,161,Juan Manuel Fangio,ARG,Maserati,40.0,1957,1
161,162,Stirling Moss,GBR,Vanwall,25.0,1957,2
162,163,Luigi Musso,ITA,Ferrari,16.0,1957,3
163,164,Mike Hawthorn,GBR,Ferrari,13.0,1957,4
164,165,Tony Brooks,GBR,Vanwall,11.0,1957,5
165,166,Masten Gregory,USA,Maserati,10.0,1957,6
166,167,Harry Schell,USA,Maserati,10.0,1957,6
167,168,Sam Hanks,USA,Epperly Offenhauser,8.0,1957,8
168,169,Peter Collins,GBR,Ferrari,8.0,1957,8
169,170,Jim Rathmann,USA,Epperly Offenhauser,7.0,1957,10
170,171,Jean Behra,FRA,Maserati,6.0,1957,11
171,172,Stuart Lewis-Evans,GBR,Vanwall,5.0,1957,12
172,173,Maurice Trintignant,FRA,Ferrari,5.0,1957,12
173,174,Carlos Menditeguy,ARG,Maserati,4.0,1957,14
174,175,Jimmy Bryan,USA,Kuzma Offenhauser,4.0,1957,14
175,176,Wolfgang von Trips,GER,Ferrari,4.0,1957,14
176,177,Paul Russo,USA,Kurtis Kraft Novi,3.0,1957,17
177,178,Andy Linden,USA,Kurtis Kraft Offenhauser,2.0,1957,18
178,179,Roy Salvadori,GBR,Cooper Climax,2.0,1957,18
179,180,Alfonso de Portago,ESP,Ferrari,1.0,1957,20
180,181,Jose Froilan Gonzalez,ARG,Ferrari,1.0,1957,20
181,182,Giorgio Scarlatti,ITA,Maserati,1.0,1957,20
182,183,Mike Hawthorn,GBR,Ferrari,42.0,1958,1
183,184,Stirling Moss,GBR,Vanwall,41.0,1958,2
184,185,Tony Brooks,GBR,Vanwall,24.0,1958,3
185,186,Roy Salvadori,GBR,Cooper Climax,15.0,1958,4
186,187,Peter Collins,GBR,Ferrari,14.0,1958,5
187,188,Harry Schell,USA,BRM,14.0,1958,5
188,189,Maurice Trintignant,FRA,Cooper Climax,12.0,1958,7
189,190,Luigi Musso,ITA,Ferrari,12.0,1958,7
190,191,Stuart Lewis-Evans,GBR,Vanwall,11.0,1958,9
191,192,Phil Hill,USA,Ferrari,9.0,1958,10
192,193,Jean Behra,FRA,BRM,9.0,1958,10
193,194,Wolfgang von Trips,GER,Ferrari,9.0,1958,10
194,195,Jimmy Bryan,USA,Epperly Offenhauser,8.0,1958,13
195,196,Juan Manuel Fangio,ARG,Maserati,7.0,1958,14
196,197,George Amick,USA,Epperly Offenhauser,6.0,1958,15
197,198,Tony Bettenhausen,USA,Epperly Offenhauser,4.0,1958,16
198,199,Johnny Boyd,USA,Kurtis Kraft Offenhauser,4.0,1958,16
199,200,Jack Brabham,AUS,Cooper Climax,3.0,1958,18
200,201,Cliff Allison,GBR,Lotus Climax,3.0,1958,18
201,202,Jo Bonnier,SWE,BRM,3.0,1958,18
202,203,Jim Rathmann,USA,Epperly Offenhauser,2.0,1958,21
203,204,Jack Brabham,AUS,Cooper Climax,31.0,1959,1
204,205,Tony Brooks,GBR,Ferrari,27.0,1959,2
205,206,Stirling Moss,GBR,Cooper Climax,25.5,1959,3
206,207,Phil Hill,USA,Ferrari,20.0,1959,4
207,208,Maurice Trintignant,FRA,Cooper Climax,19.0,1959,5
208,209,Bruce McLaren,NZL,Cooper Climax,16.5,1959,6
209,210,Dan Gurney,USA,Ferrari,13.0,1959,7
210,211,Jo Bonnier,SWE,BRM,10.0,1959,8
211,212,Masten Gregory,USA,Cooper Climax,10.0,1959,8
212,213,Rodger Ward,USA,Kurtis Kraft Offenhauser,8.0,1959,10
213,214,Jim Rathmann,USA,Watson Offenhauser,6.0,1959,11
214,215,Johnny Thomson,USA,Lesovsky Offenhauser,5.0,1959,12
215,216,Innes Ireland,GBR,Lotus Climax,5.0,1959,12
216,217,Harry Schell,USA,Cooper Climax,5.0,1959,12
217,218,Tony Bettenhausen,USA,Epperly Offenhauser,3.0,1959,15
218,219,Olivier Gendebien,BEL,Ferrari,3.0,1959,15
219,220,Paul Goldsmith,USA,Epperly Offenhauser,2.0,1959,17
220,221,Jean Behra,FRA,Ferrari,2.0,1959,17
221,222,Cliff Allison,GBR,Ferrari,2.0,1959,17
222,223,Jack Brabham,AUS,Cooper Climax,43.0,1960,1
223,224,Bruce McLaren,NZL,Cooper Climax,34.0,1960,2
224,225,Stirling Moss,GBR,Lotus Climax,19.0,1960,3
225,226,Innes Ireland,GBR,Lotus Climax,18.0,1960,4
226,227,Phil Hill,USA,Cooper Climax,16.0,1960,5
227,228,Olivier Gendebien,BEL,Cooper Climax,10.0,1960,6
228,229,Wolfgang von Trips,GER,Cooper Maserati,10.0,1960,6
229,230,Jim Rathmann,USA,Watson Offenhauser,8.0,1960,8
230,231,Richie Ginther,USA,Ferrari,8.0,1960,8
231,232,Jim Clark,GBR,Lotus Climax,8.0,1960,8
232,233,Tony Brooks,GBR,Cooper Climax,7.0,1960,11
233,234,Cliff Allison,GBR,Ferrari,6.0,1960,12
234,235,Rodger Ward,USA,Watson Offenhauser,6.0,1960,12
235,236,John Surtees,GBR,Lotus Climax,6.0,1960,12
236,237,Paul Goldsmith,USA,Epperly Offenhauser,4.0,1960,15
237,238,Graham Hill,GBR,BRM,4.0,1960,15
238,239,Willy Mairesse,BEL,Ferrari,4.0,1960,15
239,240,Jo Bonnier,SWE,BRM,4.0,1960,15
240,241,Carlos Menditeguy,ARG,Cooper Maserati,3.0,1960,19
241,242,Don Branson,USA,Phillips Offenhauser,3.0,1960,19
242,243,Henry Taylor,GBR,Cooper Climax,3.0,1960,19
243,244,Giulio Cabianca,ITA,Cooper Castellotti,3.0,1960,19
244,245,Johnny Thomson,USA,Lesovsky Offenhauser,2.0,1960,23
245,246,Eddie Johnson,USA,Trevis Offenhauser,1.0,1960,24
246,247,Lucien Bianchi,BEL,Cooper Climax,1.0,1960,24
247,248,Ron Flockhart,GBR,Cooper Climax,1.0,1960,24
248,249,Hans Herrmann,GER,Porsche,1.0,1960,24
249,250,Phil Hill,USA,Ferrari,34.0,1961,1
250,251,Wolfgang von Trips,GER,Ferrari,33.0,1961,2
251,252,Stirling Moss,GBR,Lotus Climax,21.0,1961,3
252,253,Dan Gurney,USA,Porsche,21.0,1961,3
253,254,Richie Ginther,USA,Ferrari,16.0,1961,5
254,255,Innes Ireland,GBR,Lotus Climax,12.0,1961,6
255,256,Jim Clark,GBR,Lotus Climax,11.0,1961,7
256,257,Bruce McLaren,NZL,Cooper Climax,11.0,1961,7
257,258,Giancarlo Baghetti,ITA,Ferrari,9.0,1961,9
258,259,Tony Brooks,GBR,BRM Climax,6.0,1961,10
259,260,Jack Brabham,AUS,Cooper Climax,4.0,1961,11
260,261,John Surtees,GBR,Cooper Climax,4.0,1961,11
261,262,Olivier Gendebien,BEL,Lotus Climax,3.0,1961,13
262,263,Jackie Lewis,GBR,Cooper Climax,3.0,1961,13
263,264,Jo Bonnier,SWE,Porsche,3.0,1961,13
264,265,Graham Hill,GBR,BRM Climax,3.0,1961,13
265,266,Roy Salvadori,GBR,Cooper Climax,2.0,1961,17
266,267,Graham Hill,GBR,BRM,42.0,1962,1
267,268,Jim Clark,GBR,Lotus Climax,30.0,1962,2
268,269,Bruce McLaren,NZL,Cooper Climax,27.0,1962,3
269,270,John Surtees,GBR,Lola Climax,19.0,1962,4
270,271,Dan Gurney,USA,Porsche,15.0,1962,5
271,272,Phil Hill,USA,Ferrari,14.0,1962,6
272,273,Tony Maggs,RSA,Cooper Climax,13.0,1962,7
273,274,Richie Ginther,USA,BRM,10.0,1962,8
274,275,Jack Brabham,AUS,Brabham Climax,9.0,1962,9
275,276,Trevor Taylor,GBR,Lotus Climax,6.0,1962,10
276,277,Giancarlo Baghetti,ITA,Ferrari,5.0,1962,11
277,278,Lorenzo Bandini,ITA,Ferrari,4.0,1962,12
278,279,Ricardo Rodriguez,MEX,Ferrari,4.0,1962,12
279,280,Willy Mairesse,BEL,Ferrari,3.0,1962,14
280,281,Jo Bonnier,SWE,Porsche,3.0,1962,14
281,282,Innes Ireland,GBR,Lotus Climax,2.0,1962,16
282,283,Carel Godin de Beaufort,NED,Porsche,2.0,1962,16
283,284,Masten Gregory,USA,Lotus BRM,1.0,1962,18
284,285,Neville Lederle,RSA,Lotus Climax,1.0,1962,18
285,286,Jim Clark,GBR,Lotus Climax,54.0,1963,1
286,287,Graham Hill,GBR,BRM,29.0,1963,2
287,288,Richie Ginther,USA,BRM,29.0,1963,2
288,289,John Surtees,GBR,Ferrari,22.0,1963,4
289,290,Dan Gurney,USA,Brabham Climax,19.0,1963,5
290,291,Bruce McLaren,NZL,Cooper Climax,17.0,1963,6
291,292,Jack Brabham,AUS,Brabham Climax,14.0,1963,7
292,293,Tony Maggs,RSA,Cooper Climax,9.0,1963,8
293,294,Innes Ireland,GBR,BRP BRM,6.0,1963,9
294,295,Lorenzo Bandini,ITA,Ferrari,6.0,1963,9
295,296,Jo Bonnier,SWE,Cooper Climax,6.0,1963,9
296,297,Gerhard Mitter,GER,Porsche,3.0,1963,12
297,298,Jim Hall,USA,Lotus BRM,3.0,1963,12
298,299,Carel Godin de Beaufort,NED,Porsche,2.0,1963,14
299,300,Trevor Taylor,GBR,Lotus Climax,1.0,1963,15
300,301,Ludovico Scarfiotti,ITA,Ferrari,1.0,1963,15
301,302,Jo Siffert,SUI,Lotus BRM,1.0,1963,15
302,303,Willy Mairesse,BEL,Ferrari,0.0,1963,18
303,304,Maurice Trintignant,FRA,BRM,0.0,1963,18
304,305,Tony Settember,USA,Scirocco BRM,0.0,1963,18
305,306,Lucien Bianchi,BEL,Lola Climax,0.0,1963,18
306,307,Phil Hill,USA,ATS,0.0,1963,18
307,308,Giancarlo Baghetti,ITA,ATS,0.0,1963,18
308,309,Chris Amon,NZL,Lotus BRM,0.0,1963,18
309,310,Masten Gregory,USA,Reg Parnell Racing,0.0,1963,18
310,311,Bob Anderson,GBR,Lola Climax,0.0,1963,18
311,312,Ian Raby,GBR,Gilby BRM,0.0,1963,18
312,313,John Campbell-Jones,GBR,Lola Climax,0.0,1963,18
313,314,Ian Burgess,GBR,Scirocco BRM,0.0,1963,18
314,315,Mike Hailwood,GBR,Reg Parnell Racing,0.0,1963,18
315,316,Mario de Araujo Cabral,POR,Cooper Climax,0.0,1963,18
316,317,Bernard Collomb,FRA,Lotus Climax,0.0,1963,18
317,318,Mike Spence,GBR,Lotus Climax,0.0,1963,18
318,319,Peter Broeker,CAN,Stebro Ford,0.0,1963,18
319,320,Rodger Ward,USA,Lotus BRM,0.0,1963,18
320,321,Pedro Rodriguez,MEX,Lotus Climax,0.0,1963,18
321,322,Hap Sharp,USA,Lotus BRM,0.0,1963,18
322,323,Moises Solana,MEX,BRM,0.0,1963,18
323,324,Doug Serrurier,RSA,LDS Alfa Romeo,0.0,1963,18
324,325,Trevor Blokdyk,RSA,Cooper Maserati,0.0,1963,18
325,326,Brausch Niemann,RSA,Lotus Ford,0.0,1963,18
326,327,John Love,RHO,Cooper Climax,0.0,1963,18
327,328,Ernie Pieterse,RSA,Lotus Climax,0.0,1963,18
328,329,Peter de Klerk,RSA,Alfa Romeo,0.0,1963,18
329,330,Sam Tingle,RHO,LDS Alfa Romeo,0.0,1963,18
330,331,David Prophet,GBR,Brabham Ford,0.0,1963,18
331,332,John Surtees,GBR,Ferrari,40.0,1964,1
332,333,Graham Hill,GBR,BRM,39.0,1964,2
333,334,Jim Clark,GBR,Lotus Climax,32.0,1964,3
334,335,Lorenzo Bandini,ITA,Ferrari,23.0,1964,4
335,336,Richie Ginther,USA,BRM,23.0,1964,4
336,337,Dan Gurney,USA,Brabham Climax,19.0,1964,6
337,338,Bruce McLaren,NZL,Cooper Climax,13.0,1964,7
338,339,Peter Arundell,GBR,Lotus Climax,11.0,1964,8
339,340,Jack Brabham,AUS,Brabham Climax,11.0,1964,8
340,341,Jo Siffert,SUI,Brabham BRM,7.0,1964,10
341,342,Bob Anderson,GBR,Brabham Climax,5.0,1964,11
342,343,Tony Maggs,RSA,BRM,4.0,1964,12
343,344,Mike Spence,GBR,Lotus Climax,4.0,1964,12
344,345,Innes Ireland,GBR,BRP BRM,4.0,1964,12
345,346,Jo Bonnier,SWE,Brabham Climax,3.0,1964,15
346,347,Chris Amon,NZL,Lotus BRM,2.0,1964,16
347,348,Maurice Trintignant,FRA,BRM,2.0,1964,16
348,349,Walt Hansgen,USA,Lotus Climax,2.0,1964,16
349,350,Mike Hailwood,GBR,Lotus BRM,1.0,1964,19
350,351,Phil Hill,USA,Cooper Climax,1.0,1964,19
351,352,Trevor Taylor,GBR,BRP BRM,1.0,1964,19
352,353,Pedro Rodriguez,MEX,Ferrari,1.0,1964,19
353,354,Jim Clark,GBR,Lotus Climax,54.0,1965,1
354,355,Graham Hill,GBR,BRM,40.0,1965,2
355,356,Jackie Stewart,GBR,BRM,33.0,1965,3
356,357,Dan Gurney,USA,Brabham Climax,25.0,1965,4
357,358,John Surtees,GBR,Ferrari,17.0,1965,5
358,359,Lorenzo Bandini,ITA,Ferrari,13.0,1965,6
359,360,Richie Ginther,USA,Honda,11.0,1965,7
360,361,Mike Spence,GBR,Lotus Climax,10.0,1965,8
361,362,Bruce McLaren,NZL,Cooper Climax,10.0,1965,8
362,363,Jack Brabham,AUS,Brabham Climax,9.0,1965,10
363,364,Denny Hulme,NZL,Brabham Climax,5.0,1965,11
364,365,Jo Siffert,SUI,Brabham BRM,5.0,1965,11
365,366,Jochen Rindt,AUT,Cooper Climax,4.0,1965,13
366,367,Pedro Rodriguez,MEX,Ferrari,2.0,1965,14
367,368,Ronnie Bucknum,USA,Honda,2.0,1965,14
368,369,Richard Attwood,GBR,Lotus BRM,2.0,1965,14
369,370,Jack Brabham,AUS,Brabham Repco,42.0,1966,1
370,371,John Surtees,GBR,Cooper Maserati,28.0,1966,2
371,372,Jochen Rindt,AUT,Cooper Maserati,22.0,1966,3
372,373,Denny Hulme,NZL,Brabham Repco,18.0,1966,4
373,374,Graham Hill,GBR,BRM,17.0,1966,5
374,375,Jim Clark,GBR,Lotus BRM,16.0,1966,6
375,376,Jackie Stewart,GBR,BRM,14.0,1966,7
376,377,Mike Parkes,GBR,Ferrari,12.0,1966,8
377,378,Lorenzo Bandini,ITA,Ferrari,12.0,1966,8
378,379,Ludovico Scarfiotti,ITA,Ferrari,9.0,1966,10
379,380,Richie Ginther,USA,Honda,5.0,1966,11
380,381,Dan Gurney,USA,Eagle Climax,4.0,1966,12
381,382,Mike Spence,GBR,Lotus BRM,4.0,1966,12
382,383,Bob Bondurant,USA,Eagle Weslake,3.0,1966,14
383,384,Jo Siffert,SUI,Cooper Maserati,3.0,1966,14
384,385,Bruce McLaren,NZL,McLaren Ford,3.0,1966,14
385,386,John Taylor,GBR,Brabham BRM,1.0,1966,17
386,387,Bob Anderson,GBR,Brabham Climax,1.0,1966,17
387,388,Peter Arundell,GBR,Lotus BRM,1.0,1966,17
388,389,Jo Bonnier,SWE,Cooper Maserati,1.0,1966,17
389,390,Denny Hulme,NZL,Brabham Repco,51.0,1967,1
390,391,Jack Brabham,AUS,Brabham Repco,46.0,1967,2
391,392,Jim Clark,GBR,Lotus Ford,41.0,1967,3
392,393,John Surtees,GBR,Honda,20.0,1967,4
393,394,Chris Amon,NZL,Ferrari,20.0,1967,4
394,395,Pedro Rodriguez,MEX,Cooper Maserati,15.0,1967,6
395,396,Graham Hill,GBR,Lotus Ford,15.0,1967,6
396,397,Dan Gurney,USA,Eagle Climax,13.0,1967,8
397,398,Jackie Stewart,GBR,BRM,10.0,1967,9
398,399,Mike Spence,GBR,BRM,9.0,1967,10
399,400,John Love,RHO,Cooper Climax,6.0,1967,11